-- Spud Fields — the cast (DATA only).
--
-- A bright, sunlit chunky-cartoon farm arena. Every creature here is a FLAT 2D
-- SPRITE: a horde/creep.lua archetype carrying the ATH `sprite = true` flag, which
-- tells the shared Duel to paint its texture through the emissive slot (alpha-cut)
-- and billboard the thin body slab at the iso camera each frame — exactly how the
-- knight hero already renders. So "each enemy its own texture" is pure data:
--   * texture = "Textures/modes/spud_fields/<file>.png"  (generated by
--     tools/gen_textures_spud_fields.py; engine roots image paths at Assets/).
--   * sprite  = true                                     (flat billboard sprite).
-- If a PNG is missing the creature still draws as its flat `color` silhouette.
--
-- Roles map the four level-agnostic card/spawn roles onto this cast so the shared
-- 50-card deck works here unchanged; the crow flier is sprinkled in via auto_mix.
--
-- Aesthetic: chunky cartoon, bold black outlines, vibrant saturated fills,
-- sunny daytime palette. Goofy-cute garden critters versus one heroic spud.

local Spud = {}

-- ---- Palette (0..1) — sunny farmland --------------------------------------
local C = {
    grass      = { 0.42, 0.70, 0.27 },
    grass_dk   = { 0.30, 0.54, 0.20 },
    soil       = { 0.42, 0.28, 0.17 },
    soil_dk    = { 0.28, 0.18, 0.10 },
    sky        = { 0.50, 0.78, 0.95 },
    sprout     = { 0.55, 0.82, 0.32 },
    sun        = { 0.98, 0.84, 0.28 },
    carrot     = { 0.96, 0.52, 0.16 },
    pumpkin    = { 0.96, 0.55, 0.12 },
    husk       = { 0.86, 0.74, 0.36 },
    crow       = { 0.16, 0.16, 0.20 },
    spud       = { 0.84, 0.66, 0.40 },
    leaf       = { 0.36, 0.66, 0.24 },
}
Spud.palette = C

local TEX = "Textures/modes/spud_fields/"
Spud.tex = {
    floor     = TEX .. "floor.png",
    hero      = TEX .. "hero_spud.png",
    mud       = TEX .. "mud_patch.png",
    sprout    = TEX .. "sprout.png",
    spitter   = TEX .. "seed_spitter.png",
    husk      = TEX .. "husk_knight.png",
    pumpkin   = TEX .. "pumpkin_brute.png",
    crow      = TEX .. "crow.png",
}

Spud.theme = {
    accent        = { 0.46, 0.78, 0.24, 0.95 },
    floor         = { 0.40, 0.66, 0.28 },         -- tint under the grass texture
    floor_texture = Spud.tex.floor,
    wall          = { 0.40, 0.27, 0.16 },          -- wooden field fence / soil berm
    spawn_sigil   = { 0.96, 0.84, 0.28 },          -- sunny spawn rings
    aura          = { 0.42, 0.82, 0.95, 0.5 },
    hud_title     = "SPUD FIELDS",
    win_text      = "The fields are cleared; the harvest is yours.\nPress R to run it back  -  M for menu",
    lose_text     = "The hero is dragged under the furrows.\nPress R to run it back  -  M for menu",
}

-- ---- Hero: a heroic spud knight, one flat billboard sprite ------------------
-- A 2D sprite hero: spec.billboard = true makes the shared Duel face it at the
-- iso camera (spec.billboard_parts lists which quad parts to billboard). The art
-- (weapon included) is baked into one PNG, so a single body quad is all we need.
Spud.hero_actor = {
    name = "Spud_Hero",
    scale = 1.0,
    billboard = true,
    billboard_parts = { "body" },
    parts = {
        body = {
            kind = "quad", quad_width = 1.6, quad_height = 2.05,
            position = { 0.0, 1.0, 0.0 },
            color = { 1.0, 1.0, 1.0 }, emissive = 1.0, emissive_texture = true,
            texture = Spud.tex.hero,
        },
    },
}

-- ---- The cast — five flat-sprite garden horrors -----------------------------
-- Common shape for a standing sprite: a thin body slab (depth ~0.05), the head
-- sphere hidden (scale ~0), and body_pos raised so the sprite stands on the soil.
Spud.archetypes = {
    -- SPROUT — the swarm. A tiny angry potato-sprout that legs it at the hero.
    sprout = {
        name = "Sprout", threat_cost = 1, hp = 6, dps = 2.2, range = 0.5, speed = 2.7,
        color = C.sprout, head = C.sprout,
        sprite = true, texture = Spud.tex.sprout,
        parts = 2, scale = 0.85,
        body_pos = { 0.0, 0.60, 0.0 }, body_scale = { 0.92, 1.06, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- SEED SPITTER — the ranged anchor. A sunflower-headed stalk that holds the
    -- line and pelts seeds (modelled as a stand-off damage range in the Duel).
    seed_spitter = {
        name = "Seed Spitter", threat_cost = 3, hp = 13, dps = 2.6, range = 6.0, speed = 1.1,
        color = C.sun, head = C.sun,
        sprite = true, texture = Spud.tex.spitter,
        parts = 2, scale = 1.05,
        body_pos = { 0.0, 0.70, 0.0 }, body_scale = { 1.00, 1.22, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
        hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
    },
    -- HUSK KNIGHT — the elite wall-in-miniature. Cornhusk-armoured, medium HP.
    husk_knight = {
        name = "Husk Knight", threat_cost = 4, hp = 34, dps = 6.5, range = 0.95, speed = 1.5,
        color = C.husk, head = C.husk,
        sprite = true, texture = Spud.tex.husk,
        parts = 2, scale = 1.20,
        body_pos = { 0.0, 0.78, 0.0 }, body_scale = { 1.04, 1.30, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- PUMPKIN BRUTE — the brute. A huge round pumpkin that lumbers and crushes.
    pumpkin_brute = {
        name = "Pumpkin Brute", threat_cost = 6, hp = 74, dps = 9.0, range = 1.05, speed = 1.0,
        color = C.pumpkin, head = C.pumpkin,
        sprite = true, texture = Spud.tex.pumpkin,
        parts = 2, scale = 1.60,
        body_pos = { 0.0, 0.74, 0.0 }, body_scale = { 1.30, 1.24, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- CROW — the flier. A black scarecrow-crow that ignores terrain and dives.
    crow = {
        name = "Crow", threat_cost = 2, hp = 8, dps = 3.0, range = 0.55, speed = 3.3,
        color = C.crow, head = C.crow,
        sprite = true, texture = Spud.tex.crow, flies = true,
        parts = 2, scale = 0.95,
        body_pos = { 0.0, 1.05, 0.0 }, body_scale = { 1.18, 0.86, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
}

Spud.roles = {
    swarm  = "sprout",
    ranged = "seed_spitter",
    elite  = "husk_knight",
    brute  = "pumpkin_brute",
}

return Spud
