-- Hanged Forest — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               creature's signature silhouette — no code, just data).
--   * texture = an optional "Objects/hanged_forest/foo.png" painted on a part.
--
-- The headline horde the brief asks for is all here: the FOREST WRAITH (a floating
-- melee shade that drifts between the black trees), the CORPSE ARCHER (the
-- reanimated dead — a ranged bow that looses arrows; it is also what a hanging
-- corpse becomes when the Horde ANIMATES it, see mode.lua), the ROOT TENDRIL (a
-- slow, tanky thing that hauls itself out of the soil to grab), and the HANGING
-- JUDGE (the boss — a massive figure that swings down from the canopy). They fill
-- the deck's four roles: swarm / ranged / elite / brute.
--
-- Sprite-sheet textures (forest_wraith_sheet, corpse_archer_sheet, hanging_corpse_
-- sheet, hanging_judge_sheet, root_eruption_sheet) are generated by
-- tools/gen_textures_forest.py and referenced as commented drop-ins below — the
-- same artist hand-off the other modes use. The seamless TILE textures (bark_tile /
-- ground_tile / dark_fog) ARE wired live, in mode.lua, where they tile across flat
-- geometry.

local Hf = {}

-- The HANGED FOREST palette (mirrors tools/gen_textures_forest.py exactly).
local C = {
    void   = { 0.020, 0.020, 0.020 }, -- #050505 void black
    forest = { 0.039, 0.059, 0.000 }, -- #0a0f00 dark forest
    green  = { 0.102, 0.165, 0.000 }, -- #1a2a00 deep green
    bark   = { 0.239, 0.239, 0.000 }, -- #3d3d00 dead bark
    bone   = { 0.784, 0.784, 0.627 }, -- #c8c8a0 bone white
    moon   = { 0.267, 0.267, 0.667 }, -- #4444aa moonlight
    rope   = { 0.30, 0.26, 0.16 },    -- frayed hangman's rope
}
Hf.palette = C

-- Texture paths (engine roots at Assets/). Generated by the python tool into
-- Assets/Objects/hanged_forest/, referenced here as "Objects/hanged_forest/x.png".
local TEX = "Objects/hanged_forest/"
Hf.tex = {
    bark        = TEX .. "bark_tile.png",
    ground      = TEX .. "ground_tile.png",
    corpse      = TEX .. "hanging_corpse_sheet.png",
    wraith      = TEX .. "forest_wraith_sheet.png",
    archer      = TEX .. "corpse_archer_sheet.png",
    judge       = TEX .. "hanging_judge_sheet.png",
    root        = TEX .. "root_eruption_sheet.png",
    fog         = TEX .. "dark_fog.png",
    moonlight   = TEX .. "moonlight_shaft.png",
}

Hf.theme = {
    accent = { 0.40, 0.55, 0.0, 0.95 },         -- sickly forest-green, Souls-grim UI
    floor = { 0.039, 0.059, 0.0 },
    floor_texture = Hf.tex.ground,              -- the dead-leaf soil, wired live
    wall = { 0.020, 0.020, 0.020 },
    spawn_sigil = { 0.40, 0.55, 0.0 },
    aura = { 0.30, 0.40, 0.10, 0.45 },
    hero_body = { 0.12, 0.12, 0.10 },
    hero_trim = { 0.784, 0.784, 0.627 },
    hud_title = "HANGED FOREST",
    win_text = "The branches hang empty. The forest holds its breath, and lets you pass.\nPress R to walk in again  -  M for menu",
    lose_text = "Another rope finds a throat. The forest adds one more to its harvest.\nPress R to walk in again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO survivors. mode.lua picks one (ATH_HANGED_HERO, default
-- "executioner"). Both rigs keep the standard part keys (body/head/hand_r/
-- hand_l/foot_r/foot_l/sword) so ath_art's built-in walk/attack clips animate
-- them; extra parts ride the root for flavour. Sprite-sheet skins are commented
-- drop-ins.
-- ---------------------------------------------------------------------------

Hf.heroes = {}

-- THE EXECUTIONER: a heavy, hooded headsman with a great cleaver. His signature
-- is the rope — he CUTS the hangman's lines as he passes, so the corpse pendulums
-- that swing across the path go limp and harmless (mode.lua reads class ==
-- "executioner"). The methodical answer to the swinging dead.
Hf.heroes.executioner = {
    stats = { hp_max = 124.0, dps = 20.0, cleave = 3, attack_range = 1.34, speed = 2.05, kite_speed = 2.5, armor = 1 },
    actor = {
        name = "Hf_Executioner",
        -- texture = Hf.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.52, 0.78, 0.38 }, color = { 0.10, 0.10, 0.09 }, emissive = 0.45 },
            head = { kind = "cube", position = { 0.0, 1.12, 0.0 }, scale = { 0.32, 0.32, 0.32 }, color = { 0.06, 0.06, 0.05 }, emissive = 0.4 },
            hand_r = { kind = "sphere", position = { 0.36, 0.66, 0.05 }, scale = { 0.15, 0.15, 0.15 }, color = C.bone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.36, 0.66, 0.05 }, scale = { 0.15, 0.15, 0.15 }, color = C.bone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            -- The headsman's cleaver: a broad bright blade on a haft (this is the
            -- rope-cutter; mode.lua keys the cut off the hero's attack_range).
            sword = { kind = "cube", position = { 0.42, 0.56, 0.10 }, scale = { 0.30, 0.62, 0.06 }, color = { 0.62, 0.64, 0.55 }, emissive = 1.0 },
            -- A black executioner's hood + a leather apron — the silhouette of a
            -- man who does this for a living.
            hood = { kind = "cube", position = { 0.0, 1.24, -0.02 }, scale = { 0.34, 0.20, 0.34 }, color = { 0.04, 0.04, 0.04 }, emissive = 0.25 },
            apron = { kind = "cube", position = { 0.0, 0.34, 0.20 }, scale = { 0.46, 0.46, 0.06 }, color = { 0.16, 0.13, 0.09 }, emissive = 0.3 },
            eye = { kind = "sphere", position = { 0.0, 1.12, 0.16 }, scale = { 0.18, 0.04, 0.04 }, color = { 0.55, 0.0, 0.0 }, emissive = 1.4 },
        },
    },
}

-- THE LOST WANDERER: a lean, ragged traveller who blundered into the wood. Quick
-- and light-footed — the grasping roots clutch at empty air (mode.lua gives the
-- wanderer a smaller root-grab radius and a shorter hold). The evasive answer.
Hf.heroes.lost_wanderer = {
    stats = { hp_max = 92.0, dps = 22.5, cleave = 2, attack_range = 1.18, speed = 2.7, kite_speed = 3.3 },
    actor = {
        name = "Hf_LostWanderer",
        -- texture = Hf.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.38, 0.68, 0.28 }, color = { 0.14, 0.15, 0.10 }, emissive = 0.45 },
            head = { kind = "sphere", position = { 0.0, 1.04, 0.0 }, scale = { 0.30, 0.30, 0.30 }, color = C.bone, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.30, 0.62, 0.05 }, scale = { 0.12, 0.12, 0.12 }, color = C.bone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.62, 0.05 }, scale = { 0.12, 0.12, 0.12 }, color = C.bone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.15, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.15, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.30, 0.46, 0.10 }, scale = { 0.06, 0.50, 0.06 }, color = { 0.55, 0.57, 0.52 }, emissive = 0.9 },
            -- A travel-worn cloak + hood, and a guttering lantern on a stick — the
            -- only warm light in the wood.
            cloak = { kind = "cube", position = { 0.0, 0.50, -0.16 }, scale = { 0.44, 0.72, 0.10 }, color = { 0.10, 0.10, 0.07 }, emissive = 0.25 },
            hood = { kind = "cube", position = { 0.0, 1.16, -0.04 }, scale = { 0.30, 0.16, 0.30 }, color = { 0.10, 0.10, 0.07 }, emissive = 0.25 },
            lantern = { kind = "sphere", position = { -0.34, 0.74, 0.14 }, scale = { 0.13, 0.16, 0.13 }, color = { 0.95, 0.78, 0.30 }, emissive = 1.8 },
            eye = { kind = "sphere", position = { 0.0, 1.04, 0.16 }, scale = { 0.07, 0.05, 0.04 }, color = { 0.40, 0.55, 0.0 }, emissive = 1.5 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde — everything is OF the wood: drifting shades, the strung-up dead
-- cut loose, and the roots that feed on what hangs above.
-- ---------------------------------------------------------------------------

-- The arrow a Corpse Archer looses: a long thin bolt that DROPS under gravity, so
-- the archer must lead a moving hero (projectile.gravity is honoured by creep.lua).
local function corpse_arrow()
    return {
        kind = "orb", speed = 15.0, cooldown = 1.6, start_y = 0.95, target_y = 0.55,
        particle_size = 0.16, scale = { 0.10, 0.10, 0.60 }, color = C.bone,
        emissive = 1.0, arc = 0.05, gravity = -7.0, impact = true,
        hit_radius = 0.7, flight_grace = 0.10,
        -- texture = Hf.tex... (arrows are drawn from the elongated scale)
    }
end

Hf.archetypes = {
    -- [HEADLINE] FOREST WRAITH — a floating shade that drifts out from between the
    -- black trunks and rushes the hero. It FLIES, so the roots and uneven soil mean
    -- nothing to it. The cheap, fast swarm spine of the horde.
    forest_wraith = {
        name = "Forest Wraith", threat_cost = 1, hp = 8, dps = 3.0, range = 0.62, speed = 2.6,
        color = C.green, head = C.bone, body_scale = { 0.34, 0.54, 0.24 }, head_scale = { 0.24, 0.24, 0.24 },
        parts = 2, scale = 1.0, flies = true,
        -- texture = Hf.tex.wraith,  -- 6-frame sprite-sheet drop-in
        extras = {
            { name = "Wraith_Shroud", kind = "cube", position = { 0.0, 0.30, -0.04 }, scale = { 0.40, 0.50, 0.10 }, color = C.forest, emissive = 0.7 },
            { name = "Wraith_Wisp", kind = "sphere", position = { 0.0, 0.10, 0.0 }, scale = { 0.30, 0.22, 0.24 }, color = C.green, emissive = 0.9 },
            { name = "Wraith_Claw_R", kind = "cube", position = { 0.26, 0.50, 0.10 }, scale = { 0.05, 0.30, 0.05 }, color = C.bone, emissive = 0.6, rotation = { 0.0, 0.0, 20.0 } },
            { name = "Wraith_Claw_L", kind = "cube", position = { -0.26, 0.50, 0.10 }, scale = { 0.05, 0.30, 0.05 }, color = C.bone, emissive = 0.6, rotation = { 0.0, 0.0, -20.0 } },
            { name = "Wraith_Eye_L", kind = "sphere", position = { -0.07, 0.78, 0.12 }, scale = { 0.06, 0.06, 0.04 }, color = { 0.55, 0.75, 0.0 }, emissive = 1.9 },
            { name = "Wraith_Eye_R", kind = "sphere", position = { 0.07, 0.78, 0.12 }, scale = { 0.06, 0.06, 0.04 }, color = { 0.55, 0.75, 0.0 }, emissive = 1.9 },
        },
    },
    -- [HEADLINE] CORPSE ARCHER — the reanimated dead with a half-rotted bow. It
    -- holds its distance and looses arrows that arc down on the hero. This is ALSO
    -- what a hanging corpse becomes when the Horde ANIMATES one (mode.lua drops a
    -- corpse off its rope and spawns this archetype at the spot). The ranged threat.
    corpse_archer = {
        name = "Corpse Archer", threat_cost = 3, hp = 13, dps = 2.6, range = 6.5, speed = 1.4,
        color = C.bark, head = C.bone, weapon = C.bone,
        body_scale = { 0.34, 0.56, 0.26 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.34, 0.62, 0.06 }, weapon_scale = { 0.06, 0.78, 0.06 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = corpse_arrow(),
        -- texture = Hf.tex.archer,  -- 5-frame sprite-sheet drop-in
        extras = {
            { name = "Archer_Bow", kind = "cylinder", position = { 0.36, 0.66, 0.06 }, scale = { 0.06, 0.64, 0.06 }, color = C.bone, emissive = 0.6, rotation = { 0.0, 0.0, 12.0 } },
            { name = "Archer_Rib", kind = "cube", position = { 0.0, 0.56, 0.14 }, scale = { 0.30, 0.34, 0.05 }, color = C.bone, emissive = 0.55 },
            { name = "Archer_Noose", kind = "cylinder", position = { 0.0, 0.92, 0.0 }, scale = { 0.20, 0.10, 0.20 }, color = C.rope, emissive = 0.4 },
            { name = "Archer_Eye", kind = "sphere", position = { 0.0, 0.80, 0.14 }, scale = { 0.08, 0.05, 0.04 }, color = { 0.55, 0.0, 0.0 }, emissive = 1.7 },
        },
    },
    -- [HEADLINE] ROOT TENDRIL — a thick, barbed root that hauls itself out of the
    -- soil and drags toward the hero. Slow and tough; it soaks hits and blocks the
    -- lane while the wraiths close. The deck's "elite". (The eruption FLOOR hazard
    -- is mode-owned, in mode.lua — this is the roaming creature form.)
    root_tendril = {
        name = "Root Tendril", threat_cost = 4, hp = 30, dps = 5.0, range = 1.0, speed = 1.15,
        color = C.bark, head = C.green, body_scale = { 0.42, 0.62, 0.36 }, head_pos = { 0.0, 0.74, 0.0 }, head_scale = { 0.24, 0.26, 0.24 },
        parts = 2, scale = 1.2,
        extras = {
            { name = "Root_Coil", kind = "cylinder", position = { 0.0, 0.16, 0.0 }, scale = { 0.46, 0.18, 0.46 }, color = C.forest, emissive = 0.5 },
            { name = "Root_Barb_R", kind = "cube", position = { 0.22, 0.54, 0.10 }, scale = { 0.06, 0.40, 0.06 }, color = C.green, emissive = 0.7, rotation = { 0.0, 0.0, 26.0 } },
            { name = "Root_Barb_L", kind = "cube", position = { -0.22, 0.46, 0.10 }, scale = { 0.06, 0.34, 0.06 }, color = C.green, emissive = 0.7, rotation = { 0.0, 0.0, -26.0 } },
            { name = "Root_Tip", kind = "cube", position = { 0.0, 0.92, 0.06 }, scale = { 0.16, 0.26, 0.16 }, color = C.bark, emissive = 0.6, rotation = { 18.0, 0.0, 0.0 } },
            { name = "Root_Eye", kind = "sphere", position = { 0.0, 0.74, 0.14 }, scale = { 0.07, 0.06, 0.04 }, color = { 0.55, 0.75, 0.0 }, emissive = 1.8 },
        },
    },
    -- [HEADLINE] THE HANGING JUDGE — the boss. A massive figure that hangs from the
    -- canopy by a chain at its neck and swings down to break the hero's line. Slow,
    -- vast, near-unkillable; a great noose-and-robe silhouette. The deck's "brute".
    hanging_judge = {
        name = "The Hanging Judge", threat_cost = 6, hp = 100, dps = 12.0, range = 1.16, speed = 1.0,
        color = C.forest, head = C.bone, weapon = C.bark,
        body_scale = { 0.86, 1.04, 0.66 }, head_pos = { 0.0, 1.22, -0.02 }, head_scale = { 0.40, 0.42, 0.40 },
        weapon_pos = { 0.58, 0.52, 0.06 }, weapon_scale = { 0.22, 0.92, 0.22 },
        parts = 3, scale = 2.2,
        -- texture = Hf.tex.judge,  -- 8-frame 128x256 sprite-sheet drop-in (enormous)
        extras = {
            { name = "Judge_Robe", kind = "cube", position = { 0.0, 0.40, 0.0 }, scale = { 0.96, 0.70, 0.72 }, color = C.void, emissive = 0.35 },
            { name = "Judge_Chain", kind = "cylinder", position = { 0.0, 1.70, -0.04 }, scale = { 0.10, 0.80, 0.10 }, color = C.bone, emissive = 0.6 },
            { name = "Judge_Noose", kind = "cylinder", position = { 0.0, 1.30, 0.0 }, scale = { 0.46, 0.14, 0.46 }, color = C.rope, emissive = 0.5 },
            { name = "Judge_Collar", kind = "cube", position = { 0.0, 0.94, 0.30 }, scale = { 0.60, 0.16, 0.12 }, color = C.bark, emissive = 0.5 },
            { name = "Judge_Maw", kind = "cube", position = { 0.0, 1.16, 0.30 }, scale = { 0.30, 0.10, 0.10 }, color = C.void, emissive = 0.3 },
            { name = "Judge_Eye_L", kind = "sphere", position = { -0.14, 1.28, 0.28 }, scale = { 0.12, 0.10, 0.06 }, color = { 0.65, 0.0, 0.0 }, emissive = 2.1 },
            { name = "Judge_Eye_R", kind = "sphere", position = { 0.14, 1.28, 0.28 }, scale = { 0.12, 0.10, 0.06 }, color = { 0.65, 0.0, 0.0 }, emissive = 2.1 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Hf.roles = {
    swarm = "forest_wraith",
    ranged = "corpse_archer",
    elite = "root_tendril",
    brute = "hanging_judge",
}

return Hf
