# run_smoke.ps1 — launch Ylem in PhasmaPlayer and assert it loads cleanly.
# Generated by tools/new_game.py. Writes phasma_settings.json next to the player
# exe (that is where ResolveProjectSelection looks), force-exits any stale player,
# launches with the configured graphics API, waits, then checks the engine log.
$ErrorActionPreference = "Stop"

$project   = "C:\Users\Christos\repos\PhasmaProjects\Ylem"
$api       = "dx12"
$startup   = "Assets/Scenes/main.pescene"

# Pick the newest PhasmaPlayer across build trees. The engine repo keeps several
# (build-ninja-full reads source, build-ninja-physics copies RuntimeAssets); a
# stale player 0xC0000005-crashes loading any current scene, so always run the
# most recently built one rather than a hardcoded (and possibly stale) path.
$engine = "c:\Users\Christos\repos\PhasmaEngine"
$exe = Get-ChildItem "$engine\build*\Release\PhasmaPlayer.exe" -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1 -ExpandProperty FullName
if (-not $exe) { Write-Host "SMOKE FAIL: no PhasmaPlayer.exe found under $engine\build*\Release"; exit 3 }
$exeDir = Split-Path $exe
$settings = Join-Path $exeDir "phasma_settings.json"
$log = Join-Path $exeDir "PhasmaEngine.log"

# Point the player at this project.
@{ project_path = $project; startup_scene = $startup } | ConvertTo-Json | Set-Content -Encoding UTF8 $settings

# Force-exit any stale player and clear the old log so our run is unambiguous.
Get-Process PhasmaPlayer -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500
if (Test-Path $log) { Remove-Item -Force $log -ErrorAction SilentlyContinue }

Write-Host "Launching $exe --api $api ..."
$proc = Start-Process $exe -ArgumentList '--api', $api, '--display', '1' -WorkingDirectory $exeDir -PassThru
Start-Sleep -Seconds 18

$alive = -not $proc.HasExited
if (-not $alive) { Write-Host ("SMOKE: player EXITED early code=0x{0:X8}" -f $proc.ExitCode) }
else { Write-Host "SMOKE: player ALIVE after 18s (pid=$($proc.Id))" }

$logText = ""
if (Test-Path $log) { $logText = Get-Content $log -Raw }

$sceneLoaded = $logText -match "Scene loaded from:"
$labReady    = $logText -match "\[ylem\] lab ready"
$luaErr      = ($logText -split "`n" | Where-Object { $_ -match "\[Lua\].*error" })

Write-Host "scene loaded:        $sceneLoaded"
Write-Host "lab ready:           $labReady"
if ($luaErr) { Write-Host "LUA ERRORS:"; $luaErr | ForEach-Object { Write-Host "  $_" } }

Write-Host "----- tail of PhasmaEngine.log -----"
if ($logText) { ($logText -split "`n" | Select-Object -Last 25) | ForEach-Object { Write-Host $_ } }

# Leave the player running so a human can drive WASD; pass -Stop to kill it.
if ($args -contains '-Stop' -and $alive) { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }

if ($alive -and $sceneLoaded -and -not $luaErr) { Write-Host "SMOKE PASS"; exit 0 }
Write-Host "SMOKE FAIL"; exit 1
