-- The Abyss — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus two
-- ATH extensions the shared Duel honours:
--   * extras  = a list of decorative ath_art PART specs welded on after build
--               (the creature's signature silhouette — no code, just data).
--   * texture = an optional path painted onto the body. Any part spec also takes
--               `texture = "..."`. Paths resolve under the project assets root
--               ("Assets"), so a texture written to Assets/Textures/modes/abyss/
--               is referenced as "Textures/modes/abyss/<file>.png".
--
-- To add a new horror: copy a block, retune the numbers, restyle the colours and
-- extras, and (optionally) point `texture`/part `texture` at a PNG. To re-skin an
-- existing one for art drop-in: add `texture = "..."`. No engine edits, ever.
--
-- Roles map the four level-agnostic card/spawn roles to this cast so the shared
-- 50-card deck works here unchanged.

local Abyss = {}

-- Texture root for this mode (generated by tools/gen_textures_abyss.py).
local TEX = "Textures/modes/abyss/"

-- Shared palette so the whole chasm reads as one cold, hopeless place.
-- void #000000 · deep abyss #0a0020 · midnight #1a1a2e · bone #e0e0e0 · ember #ff4400
local C = {
    void       = { 0.00, 0.00, 0.00 },
    abyss      = { 0.039, 0.00, 0.125 },
    midnight   = { 0.102, 0.102, 0.180 },
    bone       = { 0.878, 0.878, 0.878 },
    ember      = { 1.00, 0.267, 0.00 },
    spectral   = { 0.40, 0.62, 0.95 },   -- cold dead-light blue (wraith glow)
    spectral_d = { 0.16, 0.24, 0.46 },   -- dim spectral
    rot        = { 0.22, 0.20, 0.28 },   -- drowned flesh
    ash        = { 0.34, 0.32, 0.40 },   -- grey stone bone
}
Abyss.palette = C

Abyss.theme = {
    accent      = { 1.00, 0.267, 0.00, 0.95 },
    floor       = { 0.039, 0.00, 0.125 },   -- deep abyss underfoot
    wall        = { 0.102, 0.102, 0.180 },  -- midnight chasm walls
    spawn_sigil = { 0.40, 0.62, 0.95 },     -- cold spectral rifts
    aura        = { 0.30, 0.46, 0.80, 0.5 },
    hero_body   = { 0.102, 0.102, 0.180 },
    hero_trim   = { 1.00, 0.40, 0.10 },
    hud_title   = "THE ABYSS",
    win_text    = "The dark exhales. For now, the fall is over.\nPress R to descend again  •  M for menu",
    lose_text   = "You are swallowed whole by the deep.\nPress R to descend again  •  M for menu",
}

-- ---- Hero rigs --------------------------------------------------------------
-- TWO archetypes. Part keys match ath_art's walk/attack clips (body/head/hand_*/
-- foot_*/sword); extra parts ride the root for flavour. mode.lua selects one via
-- ATH_ABYSS_HERO ("falling_knight" | "void_drifter"), defaulting to the knight.

-- Falling Knight — a heavy, doomed warrior plunging in full plate. A trailing
-- cape (the "cape flap" rides the built-in root sway) and a dim ember lantern
-- are the only warmth in the void.
Abyss.hero_knight = {
    name = "Abyss_Falling_Knight",
    parts = {
        body   = { kind = "cube",   position = { 0.0, 0.56, 0.0 },  scale = { 0.50, 0.76, 0.36 }, color = C.midnight, emissive = 0.5, texture = TEX .. "hero_fall.png" },
        head   = { kind = "sphere", position = { 0.0, 1.10, 0.0 },  scale = { 0.40, 0.38, 0.40 }, color = C.ash,      emissive = 0.45 },
        hand_r = { kind = "sphere", position = { 0.33, 0.66, 0.05 },scale = { 0.16, 0.16, 0.16 }, color = C.midnight, emissive = 0.4 },
        hand_l = { kind = "sphere", position = {-0.33, 0.66, 0.05 },scale = { 0.16, 0.16, 0.16 }, color = C.midnight, emissive = 0.4 },
        foot_r = { kind = "cube",   position = { 0.13, 0.05, 0.0 }, scale = { 0.18, 0.10, 0.24 }, color = C.void,     emissive = 0.25 },
        foot_l = { kind = "cube",   position = {-0.13, 0.05, 0.0 }, scale = { 0.18, 0.10, 0.24 }, color = C.void,     emissive = 0.25 },
        sword  = { kind = "cube",   position = { 0.37, 0.50, 0.10 },scale = { 0.08, 0.70, 0.09 }, color = C.ember,    emissive = 1.6 },
        -- A long tattered cape behind the shoulders (the cape flap rides root sway).
        cape   = { kind = "cube",   position = { 0.0, 0.66, -0.22 }, scale = { 0.46, 0.78, 0.05 }, color = C.abyss, emissive = 0.6 },
        crest  = { kind = "cube",   position = { 0.0, 1.40, 0.0 },  scale = { 0.10, 0.24, 0.42 }, color = C.ember, emissive = 1.0 },
        lantern= { kind = "sphere", position = {-0.30, 0.50, 0.18 }, scale = { 0.14, 0.14, 0.14 }, color = C.ember, emissive = 1.8 },
    },
}

-- Void Drifter — a lighter, half-corporeal wanderer who GLIDES the chasm. Spectral
-- wings catch the updraughts (mode.lua grants the drifter a glide move bonus).
Abyss.hero_drifter = {
    name = "Abyss_Void_Drifter",
    parts = {
        body   = { kind = "cube",   position = { 0.0, 0.56, 0.0 },  scale = { 0.42, 0.72, 0.30 }, color = C.spectral_d, emissive = 0.7, texture = TEX .. "hero_fall.png" },
        head   = { kind = "sphere", position = { 0.0, 1.08, 0.0 },  scale = { 0.36, 0.36, 0.36 }, color = C.spectral,   emissive = 0.9 },
        hand_r = { kind = "sphere", position = { 0.30, 0.66, 0.05 },scale = { 0.14, 0.14, 0.14 }, color = C.spectral_d, emissive = 0.6 },
        hand_l = { kind = "sphere", position = {-0.30, 0.66, 0.05 },scale = { 0.14, 0.14, 0.14 }, color = C.spectral_d, emissive = 0.6 },
        foot_r = { kind = "cube",   position = { 0.11, 0.05, 0.0 }, scale = { 0.15, 0.09, 0.20 }, color = C.abyss,      emissive = 0.4 },
        foot_l = { kind = "cube",   position = {-0.11, 0.05, 0.0 }, scale = { 0.15, 0.09, 0.20 }, color = C.abyss,      emissive = 0.4 },
        sword  = { kind = "cube",   position = { 0.34, 0.50, 0.10 },scale = { 0.06, 0.64, 0.07 }, color = C.spectral,   emissive = 1.8 },
        -- Outspread spectral wings (catch the glide).
        wing_l = { kind = "cube",   position = {-0.40, 0.72, -0.10 }, scale = { 0.44, 0.30, 0.04 }, color = C.spectral, emissive = 1.1, rotation = { 0.0, 0.0, 22.0 } },
        wing_r = { kind = "cube",   position = { 0.40, 0.72, -0.10 }, scale = { 0.44, 0.30, 0.04 }, color = C.spectral, emissive = 1.1, rotation = { 0.0, 0.0, -22.0 } },
        halo   = { kind = "sphere", position = { 0.0, 0.60, -0.18 }, scale = { 0.20, 0.20, 0.08 }, color = C.spectral, emissive = 1.6 },
    },
}

-- Default rig the menu shows; mode.lua may swap it for the drifter.
Abyss.hero_actor = Abyss.hero_knight

-- ---- Projectiles ------------------------------------------------------------
local function void_bolt(color)
    return {
        kind = "orb", speed = 15.0, cooldown = 1.1, start_y = 0.85, target_y = 0.85,
        particle_size = 0.30, scale = { 0.18, 0.18, 0.42 }, color = color or C.spectral,
        emissive = 2.2, arc = 0.05, pulse = true, impact = false, gravity = -1.2,
        hit_radius = 0.7, flight_grace = 0.10,
    }
end

-- ---- The cast ---------------------------------------------------------------
Abyss.archetypes = {
    -- Gloom Mote — the cheapest chaff: a flickering scrap of dark that drifts up
    -- out of the void in swarms.
    gloom_mote = {
        name = "Gloom Mote", threat_cost = 1, hp = 7, dps = 3.0, range = 0.6, speed = 2.8,
        color = C.midnight, head = C.spectral, body_scale = { 0.32, 0.38, 0.28 }, head_scale = { 0.24, 0.22, 0.24 },
        parts = 2, scale = 0.9, flies = true,
        extras = {
            { name = "Mote_Glow", kind = "sphere", position = { 0.0, 0.42, -0.12 }, scale = { 0.16, 0.16, 0.06 }, color = C.spectral, emissive = 1.6 },
            { name = "Mote_Wisp", kind = "cube",   position = { 0.0, 0.20, -0.18 }, scale = { 0.06, 0.26, 0.04 }, color = C.spectral_d, emissive = 0.9 },
        },
    },

    -- Abyss Wraith — a fast, frail spectre that warps straight at the hero. The
    -- 6-frame warp sheet drives its body; it FLIES, ignoring the floor.
    abyss_wraith = {
        name = "Abyss Wraith", threat_cost = 1, hp = 6, dps = 2.4, range = 0.55, speed = 3.2,
        color = C.spectral_d, head = C.spectral, body_scale = { 0.40, 0.30, 0.30 },
        head_pos = { 0.0, 0.42, 0.16 }, head_scale = { 0.24, 0.22, 0.26 },
        parts = 2, scale = 0.95, flies = true,
        texture = TEX .. "wraith.png",
        extras = {
            { name = "Wraith_Shroud", kind = "cube",   position = { 0.0, 0.30, -0.10 }, scale = { 0.42, 0.50, 0.05 }, color = C.spectral_d, emissive = 1.0 },
            { name = "Wraith_Eye",    kind = "sphere", position = { 0.0, 0.46, 0.22 },  scale = { 0.10, 0.10, 0.10 }, color = C.spectral,   emissive = 2.0 },
        },
    },

    -- Hollow Seer — a ranged caster that anchors in the dark and lobs void bolts,
    -- needing line of sight before it fires.
    hollow_seer = {
        name = "Hollow Seer", threat_cost = 3, hp = 14, dps = 2.5, range = 6.0, speed = 1.1,
        color = C.abyss, head = C.spectral, weapon = C.spectral,
        body_scale = { 0.40, 0.66, 0.32 }, head_scale = { 0.30, 0.30, 0.30 },
        weapon_pos = { 0.36, 0.62, 0.08 }, weapon_scale = { 0.07, 0.86, 0.07 },
        parts = 3, scale = 1.1, hold_range = 5.5, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = void_bolt(C.spectral),
        extras = {
            { name = "Seer_Orb",  kind = "sphere", position = { 0.36, 1.14, 0.08 }, scale = { 0.22, 0.22, 0.22 }, color = C.spectral, emissive = 2.0 },
            { name = "Seer_Cowl", kind = "cube",   position = { 0.0, 0.94, 0.0 },   scale = { 0.42, 0.20, 0.36 }, color = C.void,     emissive = 0.3 },
        },
    },

    -- Chasm Stalker — a tanky elite, all stone-grey bone and reach. The wall the
    -- hero's cleave must chew through.
    chasm_stalker = {
        name = "Chasm Stalker", threat_cost = 4, hp = 34, dps = 7.0, range = 0.95, speed = 1.7,
        color = C.ash, head = C.midnight, weapon = C.void,
        body_scale = { 0.62, 0.58, 0.46 }, head_pos = { 0.0, 0.84, -0.06 }, head_scale = { 0.34, 0.30, 0.34 },
        weapon_pos = { 0.46, 0.40, 0.04 }, weapon_scale = { 0.18, 0.42, 0.16 },
        parts = 3, scale = 1.4,
        extras = {
            { name = "Stalker_Spine_L", kind = "cylinder", position = { -0.36, 0.74, -0.08 }, scale = { 0.10, 0.40, 0.10 }, color = C.bone, emissive = 0.8, rotation = { -18.0, 0.0, 0.0 } },
            { name = "Stalker_Spine_R", kind = "cylinder", position = {  0.36, 0.74, -0.08 }, scale = { 0.10, 0.40, 0.10 }, color = C.bone, emissive = 0.8, rotation = { -18.0, 0.0, 0.0 } },
            { name = "Stalker_Glare",   kind = "cube",     position = { 0.0, 0.86, 0.18 },    scale = { 0.26, 0.06, 0.04 }, color = C.spectral, emissive = 1.8 },
        },
    },

    -- Drowned Leviathan — the boss of the deep: a vast, slow, waterlogged colossus
    -- that arrives late and ends runs.
    drowned_leviathan = {
        name = "Drowned Leviathan", threat_cost = 6, hp = 64, dps = 9.0, range = 1.0, speed = 1.2,
        color = C.rot, head = C.spectral_d, weapon = C.ash,
        body_scale = { 0.76, 0.80, 0.60 }, head_pos = { 0.0, 1.06, -0.04 }, head_scale = { 0.40, 0.36, 0.40 },
        weapon_pos = { 0.50, 0.52, 0.06 }, weapon_scale = { 0.18, 0.78, 0.18 },
        parts = 3, scale = 2.0,
        extras = {
            { name = "Leviathan_Crown", kind = "cylinder", position = { 0.0, 1.38, 0.0 },  scale = { 0.50, 0.14, 0.50 }, color = C.spectral, emissive = 1.6 },
            { name = "Leviathan_Maw",   kind = "sphere",   position = { 0.0, 0.72, -0.28 },scale = { 0.34, 0.38, 0.12 }, color = C.spectral, emissive = 1.8 },
            { name = "Leviathan_Fin_L", kind = "cube",     position = { -0.46, 0.96, -0.06 }, scale = { 0.12, 0.40, 0.05 }, color = C.rot, emissive = 0.9, rotation = { 0.0, 0.0, 24.0 } },
            { name = "Leviathan_Fin_R", kind = "cube",     position = {  0.46, 0.96, -0.06 }, scale = { 0.12, 0.40, 0.05 }, color = C.rot, emissive = 0.9, rotation = { 0.0, 0.0, -24.0 } },
        },
    },
}

Abyss.roles = {
    swarm  = "gloom_mote",
    ranged = "hollow_seer",
    elite  = "chasm_stalker",
    brute  = "drowned_leviathan",
}

return Abyss
