-- Bloodtide — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               creature's signature silhouette — no code, just data).
--   * texture = an optional "Textures/modes/bloodtide/foo.png" painted on a part.
--
-- The headline horde the brief asks for is all here: the BLOOD THRALL (a melee
-- swimmer that wades up out of the tide), the LEECH WORM (a ranged maw that spits
-- from the blood's surface), the TIDE CALLER (a frail acolyte — its death feeds
-- the tide a surge; mode.lua watches for it), and the DROWNED COLOSSUS (the boss
-- that heaves up from the deep once the timer runs out). They fill the deck's
-- four roles: swarm / ranged / elite / brute.
--
-- Sprite-sheet textures (blood_thrall_sheet, leech_worm_sheet, tide_surface_sheet,
-- drowned_colossus_sheet) are generated by tools/gen_textures_bloodtide.py and
-- referenced as commented drop-ins below — the same artist hand-off the other
-- modes use. The seamless TILE textures (cliff_wall / platform / tide_surface)
-- ARE wired live, in mode.lua, where they tile across flat geometry.

local Bt = {}

-- The BLOODTIDE palette (mirrors tools/gen_textures_bloodtide.py exactly).
local C = {
    void  = { 0.020, 0.000, 0.000 }, -- #050000 abyssal black
    dark  = { 0.102, 0.000, 0.000 }, -- #1a0000 dried blood
    deep  = { 0.239, 0.000, 0.000 }, -- #3d0000 deep blood
    blood = { 0.545, 0.000, 0.000 }, -- #8b0000 blood
    fresh = { 0.800, 0.000, 0.000 }, -- #cc0000 fresh blood
    bg    = { 0.102, 0.102, 0.165 }, -- #1a1a2a cold backdrop
    bone  = { 0.74, 0.71, 0.66 },    -- waterlogged bone / pale flesh
    iron  = { 0.40, 0.42, 0.50 },    -- rusted iron / armour
    wood  = { 0.30, 0.18, 0.10 },    -- sodden driftwood
}
Bt.palette = C

-- Texture paths (engine roots at Assets/). Generated by the python tool into
-- Assets/Textures/modes/bloodtide/, referenced here as "Textures/modes/bloodtide/<file>.png".
local TEX = "Textures/modes/bloodtide/"
Bt.tex = {
    cliff = TEX .. "cliff_wall.png",
    platform = TEX .. "platform.png",
    tide = TEX .. "tide_surface_sheet.png",
    splatter = TEX .. "tide_splatter.png",
    blood_thrall = TEX .. "blood_thrall_sheet.png",
    leech_worm = TEX .. "leech_worm_sheet.png",
    drowned_colossus = TEX .. "drowned_colossus_sheet.png",
}

Bt.theme = {
    accent = { 0.80, 0.0, 0.0, 0.95 },          -- fresh-blood red, Souls-grim UI
    floor = { 0.06, 0.0, 0.0 },
    floor_texture = Bt.tex.platform,            -- the driftwood deck, wired live
    wall = { 0.10, 0.0, 0.0 },
    spawn_sigil = { 0.80, 0.0, 0.0 },
    aura = { 0.55, 0.0, 0.0, 0.45 },
    hero_body = { 0.40, 0.42, 0.50 },
    hero_trim = { 0.74, 0.71, 0.66 },
    hud_title = "BLOODTIDE",
    win_text = "The tide stills. Its surface forgets your name.\nPress R to wade in again  -  M for menu",
    lose_text = "The red closes over the hero's head. He does not rise.\nPress R to wade in again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO survivors. mode.lua picks one (ATH_BLOODTIDE_HERO, default
-- "tide_runner"). Both rigs keep the standard part keys (body/head/hand_r/
-- hand_l/foot_r/foot_l/sword) so ath_art's built-in walk/attack clips animate
-- them; extra parts ride the root for flavour. Sprite-sheet skins are commented
-- drop-ins.
-- ---------------------------------------------------------------------------

Bt.heroes = {}

-- TIDE RUNNER: lean and quick. Frail, but outpaces the rising blood — leaps
-- platform to platform before a ledge drowns. The reflexive answer to the tide.
Bt.heroes.tide_runner = {
    stats = { hp_max = 88.0, dps = 23.0, cleave = 2, attack_range = 1.20, speed = 2.65, kite_speed = 3.25 },
    actor = {
        name = "Bt_TideRunner",
        -- texture = Bt.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.40, 0.70, 0.30 }, color = { 0.18, 0.04, 0.04 }, emissive = 0.5 },
            head = { kind = "sphere", position = { 0.0, 1.06, 0.0 }, scale = { 0.32, 0.32, 0.32 }, color = C.bone, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.bone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.bone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.32, 0.46, 0.10 }, scale = { 0.06, 0.52, 0.06 }, color = C.iron, emissive = 0.9 },
            -- A coil of rope + a hood — the silhouette of someone who came to survive.
            hood = { kind = "cube", position = { 0.0, 1.20, -0.02 }, scale = { 0.30, 0.16, 0.30 }, color = { 0.14, 0.02, 0.02 }, emissive = 0.3 },
            rope = { kind = "cylinder", position = { -0.20, 0.58, 0.10 }, scale = { 0.22, 0.10, 0.22 }, color = C.wood, emissive = 0.4, rotation = { 90.0, 0.0, 0.0 } },
            eye = { kind = "sphere", position = { 0.0, 1.06, 0.16 }, scale = { 0.07, 0.05, 0.04 }, color = C.fresh, emissive = 1.6 },
        },
    },
}

-- IRON WILL SURVIVOR: heavy, shielded, stubborn. Slow, but tanks the tide's
-- touch and wades where the Runner would drown — the attrition answer.
Bt.heroes.iron_will_survivor = {
    stats = { hp_max = 132.0, dps = 18.5, cleave = 3, attack_range = 1.32, speed = 2.00, kite_speed = 2.45, armor = 1 },
    actor = {
        name = "Bt_IronWill",
        -- texture = Bt.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.54, 0.80, 0.40 }, color = C.iron, emissive = 0.55 },
            head = { kind = "cube", position = { 0.0, 1.12, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.iron, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.36, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.bone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.36, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.bone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.40, 0.52, 0.10 }, scale = { 0.09, 0.74, 0.10 }, color = C.iron, emissive = 0.9 },
            -- A great tower shield + visor — the wall he holds against the red.
            shield = { kind = "cube", position = { -0.40, 0.60, 0.16 }, scale = { 0.12, 0.66, 0.46 }, color = C.iron, emissive = 0.6 },
            shield_boss = { kind = "sphere", position = { -0.46, 0.60, 0.16 }, scale = { 0.14, 0.14, 0.14 }, color = C.blood, emissive = 1.0 },
            visor = { kind = "cube", position = { 0.0, 1.12, 0.18 }, scale = { 0.30, 0.06, 0.04 }, color = C.void, emissive = 0.2 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde — everything is OF the tide: drowned, leeched, bloated, swollen.
-- ---------------------------------------------------------------------------

-- The gout a Leech Worm spits: a bolt of blood lobbed up off the surface, so it
-- arcs and DROPS under gravity (projectile.gravity is honoured by creep.lua).
local function leech_spit()
    return {
        kind = "orb", speed = 12.0, cooldown = 1.6, start_y = 0.35, target_y = 0.55,
        particle_size = 0.20, scale = { 0.20, 0.20, 0.20 }, color = C.fresh,
        emissive = 1.2, arc = 0.20, gravity = -7.5, impact = true,
        hit_radius = 0.75, flight_grace = 0.10,
        -- texture = Bt.tex... (the gout is drawn from the orb scale)
    }
end

Bt.archetypes = {
    -- [HEADLINE] BLOOD THRALL — a drowned wretch that hauls itself out of the
    -- tide and swims at the hero. The cheap, fast swarm spine of the horde.
    blood_thrall = {
        name = "Blood Thrall", threat_cost = 1, hp = 9, dps = 3.0, range = 0.60, speed = 2.45,
        color = C.deep, head = C.bone, body_scale = { 0.34, 0.50, 0.26 }, head_scale = { 0.24, 0.24, 0.24 },
        parts = 2, scale = 1.0,
        -- texture = Bt.tex.blood_thrall,  -- 6-frame sprite-sheet drop-in
        extras = {
            { name = "Thrall_Drip", kind = "cube", position = { 0.0, 0.30, 0.0 }, scale = { 0.30, 0.10, 0.24 }, color = C.fresh, emissive = 0.9 },
            { name = "Thrall_Claw_R", kind = "cube", position = { 0.24, 0.52, 0.10 }, scale = { 0.05, 0.34, 0.05 }, color = C.bone, emissive = 0.6, rotation = { 0.0, 0.0, 18.0 } },
            { name = "Thrall_Claw_L", kind = "cube", position = { -0.24, 0.52, 0.10 }, scale = { 0.05, 0.30, 0.05 }, color = C.bone, emissive = 0.6, rotation = { 0.0, 0.0, -18.0 } },
            { name = "Thrall_Eye", kind = "sphere", position = { 0.0, 0.82, 0.12 }, scale = { 0.10, 0.06, 0.04 }, color = C.fresh, emissive = 1.7 },
        },
    },
    -- [HEADLINE] LEECH WORM — a bloated maw that floats on the surface and spits
    -- arcing gouts of blood. The ranged threat; holds the deep water and pesters
    -- the hero off his platforms.
    leech_worm = {
        name = "Leech Worm", threat_cost = 3, hp = 12, dps = 2.4, range = 6.5, speed = 1.05,
        color = C.blood, head = C.fresh, weapon = C.fresh,
        body_scale = { 0.46, 0.34, 0.30 }, head_pos = { 0.0, 0.40, 0.18 }, head_scale = { 0.28, 0.26, 0.26 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        weapon_pos = { 0.0, 0.42, 0.30 }, weapon_scale = { 0.18, 0.18, 0.18 },
        projectile = leech_spit(),
        -- texture = Bt.tex.leech_worm,  -- 4-frame sprite-sheet drop-in
        extras = {
            { name = "Worm_Maw", kind = "sphere", position = { 0.0, 0.40, 0.30 }, scale = { 0.26, 0.22, 0.18 }, color = C.dark, emissive = 0.6 },
            { name = "Worm_Tooth_1", kind = "cube", position = { -0.07, 0.40, 0.40 }, scale = { 0.04, 0.10, 0.04 }, color = C.bone, emissive = 0.8 },
            { name = "Worm_Tooth_2", kind = "cube", position = { 0.07, 0.40, 0.40 }, scale = { 0.04, 0.10, 0.04 }, color = C.bone, emissive = 0.8 },
            { name = "Worm_Coil", kind = "cylinder", position = { 0.0, 0.18, -0.12 }, scale = { 0.40, 0.14, 0.40 }, color = C.deep, emissive = 0.7 },
            { name = "Worm_Eye", kind = "sphere", position = { 0.0, 0.56, 0.20 }, scale = { 0.08, 0.08, 0.05 }, color = C.fresh, emissive = 1.8 },
        },
    },
    -- [HEADLINE] TIDE CALLER — a gaunt acolyte that chants the blood higher. It
    -- barely fights; the danger is its DEATH — when it falls, its severed will
    -- spills into the tide and SURGES it (mode.lua watches for tide_caller deaths
    -- in on_combat_tick). Kill it and you pay in water. The deck's "elite".
    tide_caller = {
        name = "Tide Caller", threat_cost = 4, hp = 26, dps = 4.0, range = 1.0, speed = 1.30,
        color = C.dark, head = C.deep, body_scale = { 0.40, 0.66, 0.30 }, head_pos = { 0.0, 0.78, 0.0 }, head_scale = { 0.26, 0.28, 0.26 },
        parts = 2, scale = 1.20,
        extras = {
            { name = "Caller_Robe", kind = "cube", position = { 0.0, 0.30, 0.0 }, scale = { 0.46, 0.40, 0.36 }, color = C.deep, emissive = 0.7 },
            { name = "Caller_Staff", kind = "cylinder", position = { 0.30, 0.70, 0.08 }, scale = { 0.05, 0.90, 0.05 }, color = C.wood, emissive = 0.5 },
            { name = "Caller_Sigil", kind = "sphere", position = { 0.30, 1.18, 0.08 }, scale = { 0.18, 0.18, 0.12 }, color = C.fresh, emissive = 1.9 },
            { name = "Caller_Cowl", kind = "cube", position = { 0.0, 0.92, -0.02 }, scale = { 0.30, 0.20, 0.30 }, color = C.void, emissive = 0.3 },
            { name = "Caller_Eye_L", kind = "sphere", position = { -0.07, 0.80, 0.14 }, scale = { 0.06, 0.05, 0.04 }, color = C.fresh, emissive = 1.8 },
            { name = "Caller_Eye_R", kind = "sphere", position = { 0.07, 0.80, 0.14 }, scale = { 0.06, 0.05, 0.04 }, color = C.fresh, emissive = 1.8 },
        },
    },
    -- [HEADLINE] DROWNED COLOSSUS — a leviathan of bloated dead, heaving up from
    -- the deep once the timer is spent. Slow, vast, and nearly unkillable; it
    -- breaks the survivor's line. The deck's "brute".
    drowned_colossus = {
        name = "Drowned Colossus", threat_cost = 6, hp = 90, dps = 11.0, range = 1.10, speed = 1.05,
        color = C.deep, head = C.dark, weapon = C.blood,
        body_scale = { 0.84, 0.90, 0.66 }, head_pos = { 0.0, 1.12, -0.04 }, head_scale = { 0.40, 0.38, 0.40 },
        weapon_pos = { 0.54, 0.50, 0.06 }, weapon_scale = { 0.20, 0.84, 0.20 },
        parts = 3, scale = 2.05,
        -- texture = Bt.tex.drowned_colossus,  -- 8-frame 128x128 sprite-sheet drop-in
        extras = {
            { name = "Colossus_Barnacle_L", kind = "sphere", position = { -0.30, 0.70, 0.30 }, scale = { 0.18, 0.18, 0.18 }, color = C.bone, emissive = 0.6 },
            { name = "Colossus_Barnacle_R", kind = "sphere", position = { 0.28, 0.50, 0.32 }, scale = { 0.16, 0.16, 0.16 }, color = C.bone, emissive = 0.6 },
            { name = "Colossus_Ribs", kind = "cube", position = { 0.0, 0.74, 0.34 }, scale = { 0.56, 0.50, 0.06 }, color = C.bone, emissive = 0.6 },
            { name = "Colossus_Maw", kind = "cube", position = { 0.0, 1.06, 0.22 }, scale = { 0.28, 0.10, 0.10 }, color = C.void, emissive = 0.4 },
            { name = "Colossus_Eye_L", kind = "sphere", position = { -0.12, 1.16, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.fresh, emissive = 2.0 },
            { name = "Colossus_Eye_R", kind = "sphere", position = { 0.12, 1.16, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.fresh, emissive = 2.0 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Bt.roles = {
    swarm = "blood_thrall",
    ranged = "leech_worm",
    elite = "tide_caller",
    brute = "drowned_colossus",
}

return Bt
