-- The Tower — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               creature's signature silhouette — no code, just data).
--   * texture = an optional "Textures/modes/tower/foo.png" painted on a part.
--
-- The headline horde cast the brief asks for is here: the GARGOYLE (a dive-bombing
-- flier), the CURSED KNIGHT (the tanky floor guardian), the CHANDELIER TRAP (a slow
-- falling-AoE menace) and the STONE GOLEM (the floor-8 boss). A ranged HOLLOW
-- ARBALEST rounds the cast out so the shared 50-card deck's four roles all resolve.
--
-- Sprite-sheet textures (gargoyle_sheet.png, cursed_knight_sheet.png, golem_sheet
-- .png, chandelier.png, ...) are generated by tools/gen_textures_tower.py and are
-- referenced as commented drop-ins below — the same artist hand-off the other modes
-- use. The seamless TILE textures (stone_tile / window_tile) ARE wired live in
-- mode.lua, where they tile across the floor and the climbing backdrop shaft.

local Tower = {}

-- The TOWER palette (mirrors tools/gen_textures_tower.py exactly).
local C = {
    black  = { 0.051, 0.051, 0.051 }, -- #0d0d0d   pitch dark
    plum   = { 0.165, 0.102, 0.165 }, -- #2a1a2a   crumbling mortar
    stone  = { 0.290, 0.227, 0.290 }, -- #4a3a4a   gothic stonework
    steel  = { 0.541, 0.541, 0.667 }, -- #8a8aaa   pale steel / bone
    fire   = { 1.000, 0.267, 0.000 }, -- #ff4400   torch / ember
    gold   = { 1.000, 0.843, 0.000 }, -- #ffd700   candlelight / curse-gold
    curse  = { 0.62, 0.22, 0.58 },    -- sickly arcane glow (eyes, runes)
}
Tower.palette = C

-- Texture paths (engine roots at Assets/). Generated by the python tool into
-- Assets/Textures/modes/tower/ , so the Lua side references them as "Textures/modes/tower/...".
local TEX = "Textures/modes/tower/"
Tower.tex = {
    stone = TEX .. "stone_tile.png",
    window = TEX .. "window_tile.png",
    gargoyle = TEX .. "gargoyle_sheet.png",
    cursed_knight = TEX .. "cursed_knight_sheet.png",
    golem = TEX .. "golem_sheet.png",
    chandelier = TEX .. "chandelier.png",
    crack = TEX .. "crack_overlay.png",
    torch = TEX .. "torch_sconce.png",
}

Tower.theme = {
    accent = { 1.0, 0.267, 0.0, 0.95 },         -- ember-orange, like a Souls bonfire UI
    floor = { 0.10, 0.08, 0.10 },
    floor_texture = Tower.tex.stone,            -- gothic flagstone, wired live
    wall = { 0.165, 0.102, 0.165 },
    spawn_sigil = { 0.62, 0.22, 0.58 },         -- cursed summoning runes
    aura = { 1.0, 0.4, 0.1, 0.45 },
    hero_body = { 0.290, 0.227, 0.290 },
    hero_trim = { 0.541, 0.541, 0.667 },
    hud_title = "THE TOWER",
    win_text = "The summit is silent. The tower keeps its dead.\nPress R to climb again  -  M for menu",
    lose_text = "The hero is dashed down the stairwell.\nPress R to climb again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO classes. mode.lua picks one (ATH_TOWER_CLASS, default "climber").
-- Both rigs keep the standard part keys (body/head/hand_r/hand_l/foot_r/foot_l/
-- sword) so ath_art's built-in walk/attack clips animate them; extra parts ride
-- the root for flavour. Sprite-sheet skins are commented drop-ins.
-- ---------------------------------------------------------------------------

Tower.heroes = {}

-- The TOWER CLIMBER: heavy, lantern-bearing, armoured. Slow but durable — the
-- knight who means to reach the top.
Tower.heroes.climber = {
    stats = { hp_max = 124.0, dps = 19.0, cleave = 3, attack_range = 1.30, speed = 2.10, kite_speed = 2.5 },
    actor = {
        name = "Tower_Climber",
        -- texture = Tower.tex.climber,  -- artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.52, 0.78, 0.38 }, color = C.stone, emissive = 0.55 },
            head = { kind = "cube", position = { 0.0, 1.10, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.stone, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.34, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.steel, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.34, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.steel, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.38, 0.52, 0.10 }, scale = { 0.09, 0.74, 0.10 }, color = C.steel, emissive = 0.9 },
            visor = { kind = "cube", position = { 0.0, 1.10, 0.18 }, scale = { 0.30, 0.06, 0.04 }, color = C.black, emissive = 0.2 },
            crest = { kind = "cube", position = { 0.0, 1.34, 0.0 }, scale = { 0.06, 0.18, 0.10 }, color = C.fire, emissive = 1.3 },
            lantern = { kind = "sphere", position = { -0.40, 0.74, 0.10 }, scale = { 0.16, 0.18, 0.16 }, color = C.gold, emissive = 1.7 },
        },
    },
}

-- The CURSED WANDERER: lean, fast, hollowed. Frail but high-DPS and slippery — a
-- branded undead who climbs out of habit, not hope.
Tower.heroes.wanderer = {
    stats = { hp_max = 84.0, dps = 26.0, cleave = 2, attack_range = 1.15, speed = 2.50, kite_speed = 3.1, dash = 1 },
    actor = {
        name = "Cursed_Wanderer",
        -- texture = Tower.tex.wanderer,  -- artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.40, 0.70, 0.30 }, color = C.plum, emissive = 0.5 },
            head = { kind = "sphere", position = { 0.0, 1.06, 0.0 }, scale = { 0.34, 0.34, 0.34 }, color = C.plum, emissive = 0.45 },
            hand_r = { kind = "sphere", position = { 0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.steel, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.steel, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.32, 0.46, 0.10 }, scale = { 0.06, 0.54, 0.06 }, color = C.steel, emissive = 0.9 },
            hood = { kind = "cube", position = { 0.0, 1.22, -0.02 }, scale = { 0.30, 0.18, 0.30 }, color = C.black, emissive = 0.3 },
            eye_l = { kind = "sphere", position = { -0.08, 1.06, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.curse, emissive = 1.7 },
            eye_r = { kind = "sphere", position = { 0.08, 1.06, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.curse, emissive = 1.7 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde. A gargoyle-and-grave aesthetic throughout (extras give silhouette).
-- ---------------------------------------------------------------------------

-- The bolt a Hollow Arbalest looses: a long thin quarrel that DROPS under gravity,
-- so it must lead a moving hero (projectile.gravity is honoured by creep.lua).
local function cursed_bolt()
    return {
        kind = "orb", speed = 15.0, cooldown = 1.5, start_y = 1.0, target_y = 0.55,
        particle_size = 0.18, scale = { 0.10, 0.10, 0.58 }, color = C.curse,
        emissive = 1.4, arc = 0.05, gravity = -6.5, impact = true,
        hit_radius = 0.7, flight_grace = 0.10,
    }
end

Tower.archetypes = {
    -- [HEADLINE] GARGOYLE — a winged stone devil that pours off the rafters. Cheap,
    -- fast and FLYING (flies = true), so it beelines over rubble straight at the
    -- hero. The mode's signature dive-bomb hazard is the same beast made airborne.
    gargoyle = {
        name = "Gargoyle", threat_cost = 1, hp = 9, dps = 3.2, range = 0.6, speed = 2.9,
        color = C.stone, head = C.stone, body_scale = { 0.36, 0.40, 0.30 }, head_scale = { 0.24, 0.22, 0.24 },
        parts = 2, scale = 0.95, flies = true,
        -- texture = Tower.tex.gargoyle,  -- 6-frame sprite-sheet drop-in (perch+dive)
        extras = {
            { name = "Garg_Wing_L", kind = "cube", position = { -0.34, 0.52, -0.04 }, scale = { 0.30, 0.04, 0.20 }, color = C.plum, emissive = 0.6, rotation = { 0.0, 0.0, 24.0 } },
            { name = "Garg_Wing_R", kind = "cube", position = { 0.34, 0.52, -0.04 }, scale = { 0.30, 0.04, 0.20 }, color = C.plum, emissive = 0.6, rotation = { 0.0, 0.0, -24.0 } },
            { name = "Garg_Horn", kind = "cylinder", position = { 0.0, 0.78, 0.0 }, scale = { 0.08, 0.18, 0.08 }, color = C.steel, emissive = 0.7 },
            { name = "Garg_Eye", kind = "sphere", position = { 0.0, 0.56, 0.14 }, scale = { 0.09, 0.06, 0.04 }, color = C.fire, emissive = 1.8 },
        },
    },
    -- [HEADLINE] HOLLOW ARBALEST — ranged undead; arcs gravity-dropping quarrels
    -- from the back rank so the line in front shields it.
    hollow_arbalest = {
        name = "Hollow Arbalest", threat_cost = 3, hp = 13, dps = 2.6, range = 6.5, speed = 1.2,
        color = C.plum, head = C.steel, weapon = C.stone,
        body_scale = { 0.36, 0.58, 0.28 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.34, 0.60, 0.06 }, weapon_scale = { 0.07, 0.46, 0.07 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = cursed_bolt(),
        extras = {
            { name = "Arb_Stock", kind = "cube", position = { 0.32, 0.62, 0.14 }, scale = { 0.36, 0.07, 0.08 }, color = C.stone, emissive = 0.6 },
            { name = "Arb_Bow", kind = "cube", position = { 0.46, 0.62, 0.14 }, scale = { 0.06, 0.40, 0.06 }, color = C.steel, emissive = 0.7 },
            { name = "Arb_Eye", kind = "sphere", position = { 0.0, 0.92, 0.12 }, scale = { 0.09, 0.06, 0.04 }, color = C.curse, emissive = 1.7 },
        },
    },
    -- [HEADLINE] CURSED KNIGHT — the floor guardian. Tanky, armoured and slow; the
    -- wall the hero's cleave must chew through to clear a floor and free the stairs.
    cursed_knight = {
        name = "Cursed Knight", threat_cost = 4, hp = 42, dps = 8.0, range = 1.0, speed = 1.55,
        color = C.stone, head = C.steel, weapon = C.steel,
        body_scale = { 0.60, 0.60, 0.46 }, head_pos = { 0.0, 0.86, -0.04 }, head_scale = { 0.32, 0.30, 0.32 },
        weapon_pos = { 0.46, 0.46, 0.04 }, weapon_scale = { 0.10, 0.82, 0.10 },
        parts = 3, scale = 1.4,
        -- texture = Tower.tex.cursed_knight,  -- 8-frame sprite-sheet drop-in
        extras = {
            { name = "Knight_Pauldron_L", kind = "sphere", position = { -0.40, 0.64, 0.0 }, scale = { 0.24, 0.20, 0.24 }, color = C.plum, emissive = 0.7 },
            { name = "Knight_Pauldron_R", kind = "sphere", position = { 0.40, 0.64, 0.0 }, scale = { 0.24, 0.20, 0.24 }, color = C.plum, emissive = 0.7 },
            { name = "Knight_Plume", kind = "cube", position = { 0.0, 1.12, -0.02 }, scale = { 0.06, 0.22, 0.10 }, color = C.fire, emissive = 1.2 },
            { name = "Knight_Visor", kind = "cube", position = { 0.0, 0.88, 0.16 }, scale = { 0.26, 0.05, 0.04 }, color = C.curse, emissive = 1.6 },
        },
    },
    -- [HEADLINE] CHANDELIER TRAP — a cursed iron candle-wheel that lurches along the
    -- floor on a broken chain, dropping a heavy candle-fall AoE menace into the
    -- ranks. Slow and tanky: the mobile cousin of mode.lua's falling-chandelier
    -- hazard, so the horde can deploy one as a unit.
    chandelier_trap = {
        name = "Chandelier Trap", threat_cost = 4, hp = 36, dps = 7.0, range = 1.1, speed = 0.6,
        color = C.stone, head = C.gold, body_scale = { 0.64, 0.30, 0.62 }, head_pos = { 0.0, 0.44, 0.0 }, head_scale = { 0.20, 0.16, 0.20 },
        parts = 2, scale = 1.35,
        extras = {
            { name = "Chand_Ring", kind = "cylinder", position = { 0.0, 0.34, 0.0 }, scale = { 0.66, 0.06, 0.66 }, color = C.steel, emissive = 0.7 },
            { name = "Chand_Chain", kind = "cube", position = { 0.0, 0.78, 0.0 }, scale = { 0.05, 0.50, 0.05 }, color = C.stone, emissive = 0.5 },
            { name = "Chand_Candle_1", kind = "cylinder", position = { -0.28, 0.46, -0.18 }, scale = { 0.08, 0.22, 0.08 }, color = C.steel, emissive = 0.6 },
            { name = "Chand_Candle_2", kind = "cylinder", position = { 0.28, 0.46, -0.10 }, scale = { 0.08, 0.22, 0.08 }, color = C.steel, emissive = 0.6 },
            { name = "Chand_Candle_3", kind = "cylinder", position = { 0.0, 0.46, 0.28 }, scale = { 0.08, 0.22, 0.08 }, color = C.steel, emissive = 0.6 },
            { name = "Chand_Flame", kind = "sphere", position = { 0.0, 0.64, 0.0 }, scale = { 0.18, 0.22, 0.18 }, color = C.gold, emissive = 1.8 },
        },
    },
    -- [HEADLINE] STONE GOLEM — the floor-8 boss. A colossus of mortared rubble that
    -- arrives at the summit and breaks any line. Slow, brutal, mountainous.
    stone_golem = {
        name = "Stone Golem", threat_cost = 7, hp = 96, dps = 11.0, range = 1.1, speed = 1.05,
        color = C.stone, head = C.plum, weapon = C.stone,
        body_scale = { 0.84, 0.86, 0.66 }, head_pos = { 0.0, 1.10, -0.04 }, head_scale = { 0.42, 0.40, 0.42 },
        weapon_pos = { 0.54, 0.50, 0.06 }, weapon_scale = { 0.24, 0.50, 0.24 },
        parts = 3, scale = 2.1,
        -- texture = Tower.tex.golem,  -- 6-frame 128x128 sprite-sheet drop-in
        extras = {
            { name = "Golem_Boulder_L", kind = "sphere", position = { -0.46, 0.70, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.plum, emissive = 0.6 },
            { name = "Golem_Boulder_R", kind = "sphere", position = { 0.46, 0.70, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.plum, emissive = 0.6 },
            { name = "Golem_Core", kind = "sphere", position = { 0.0, 0.74, 0.28 }, scale = { 0.30, 0.36, 0.12 }, color = C.fire, emissive = 2.0 },
            { name = "Golem_Eye_L", kind = "sphere", position = { -0.14, 1.14, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.fire, emissive = 1.9 },
            { name = "Golem_Eye_R", kind = "sphere", position = { 0.14, 1.14, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.fire, emissive = 1.9 },
            { name = "Golem_Crown", kind = "cube", position = { 0.0, 1.40, 0.0 }, scale = { 0.46, 0.10, 0.46 }, color = C.steel, emissive = 0.8 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Tower.roles = {
    swarm = "gargoyle",
    ranged = "hollow_arbalest",
    elite = "cursed_knight",
    brute = "stone_golem",
}

return Tower
