-- Condemned — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               jailer/guard silhouette — no code, just data).
--   * texture = an optional "Textures/modes/condemned/foo.png" painted on a part.
--
-- The headline gaol cast the brief asks for is here: the DUNGEON GUARD (patrolling
-- melee), the JAILER (slow, tanky, key-holder elite) and the WARDEN (the boss that
-- hunts the hero down the final block). Two more variants — a PRISON HOUND chaser
-- and a CROSSBOW SENTRY — round the cast out so the shared 50-card deck's four
-- roles all resolve.
--
-- Sprite-sheet textures (guard_sheet.png, convict_sheet.png, warden_sheet.png,
-- torch_sheet.png) are generated by tools/gen_textures_condemned.py and referenced
-- as commented drop-ins below — the same artist hand-off the other modes use. The
-- seamless TILE textures (wall_tile / bars_tile) ARE wired live, in mode.lua,
-- where they tile across flat geometry instead of a single body cube.

local Cond = {}

-- The CONDEMNED palette (mirrors tools/gen_textures_condemned.py exactly).
local C = {
    black  = { 0.067, 0.067, 0.067 }, -- #111111 prison black
    stone  = { 0.173, 0.173, 0.173 }, -- #2c2c2c stone
    metal  = { 0.290, 0.290, 0.290 }, -- #4a4a4a iron / bars
    blood  = { 0.545, 0.0, 0.0 },     -- #8b0000 dried blood
    torch  = { 1.0, 0.40, 0.0 },      -- #ff6600 torch fire
    pale   = { 0.66, 0.63, 0.58 },    -- prisoner skin / weathered bone
    rust   = { 0.40, 0.26, 0.15 },    -- corroded iron fittings
}
Cond.palette = C

-- Texture paths (the engine roots texture paths at Assets/, so these resolve to
-- Assets/Textures/modes/condemned/<file>.png). Generated by the python tool.
local TEX = "Textures/modes/condemned/"
Cond.tex = {
    wall = TEX .. "wall_tile.png",
    bars = TEX .. "bars_tile.png",
    background = TEX .. "background.png",
    guard = TEX .. "guard_sheet.png",
    convict = TEX .. "convict_sheet.png",
    knight = TEX .. "knight_sheet.png",
    warden = TEX .. "warden_sheet.png",
    torch = TEX .. "torch_sheet.png",
    lever = TEX .. "lever_sheet.png",
    portal = TEX .. "portal.png",
}

Cond.theme = {
    accent = { 0.55, 0.0, 0.0, 0.95 },          -- gaol blood-red UI
    floor = { 0.09, 0.09, 0.09 },
    floor_texture = Cond.tex.wall,              -- the cell flagstone, wired live
    wall = { 0.12, 0.12, 0.12 },
    spawn_sigil = { 0.55, 0.0, 0.0 },
    aura = { 0.55, 0.05, 0.05, 0.45 },
    hero_body = { 0.173, 0.173, 0.173 },
    hero_trim = { 0.290, 0.290, 0.290 },
    hud_title = "CONDEMNED",
    win_text = "The last gate yawns open. You walk free into the dark.\nPress R to break out again  -  M for menu",
    lose_text = "The bars slam shut for the last time. You die in your cell.\nPress R to break out again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO classes. mode.lua picks one (ATH_COND_CLASS, default "convict").
-- Both rigs keep the standard part keys (body/head/hand_r/hand_l/foot_r/foot_l/
-- sword) so ath_art's built-in walk/attack clips animate them; extra parts ride
-- the root for flavour. Sprite-sheet skins are commented drop-ins.
-- ---------------------------------------------------------------------------

Cond.heroes = {}

-- The CONVICT: lean, fast, desperate. Frail but high-DPS — sprints the blocks,
-- a shiv in each hand and a chained manacle still on one wrist.
Cond.heroes.convict = {
    stats = { hp_max = 80.0, dps = 26.0, cleave = 2, attack_range = 1.15, speed = 2.6, kite_speed = 3.2, dash = 1 },
    actor = {
        name = "Cond_Convict",
        -- texture = Cond.tex.convict,  -- 4-frame artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.40, 0.70, 0.30 }, color = C.stone, emissive = 0.5 },
            head = { kind = "sphere", position = { 0.0, 1.04, 0.0 }, scale = { 0.32, 0.32, 0.32 }, color = C.pale, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.pale, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.pale, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.32, 0.50, 0.10 }, scale = { 0.06, 0.42, 0.06 }, color = C.metal, emissive = 0.9 },
            shiv_l = { kind = "cube", position = { -0.32, 0.50, 0.10 }, scale = { 0.05, 0.34, 0.05 }, color = C.metal, emissive = 0.9 },
            stripe = { kind = "cube", position = { 0.0, 0.58, 0.16 }, scale = { 0.42, 0.10, 0.04 }, color = C.torch, emissive = 0.9 },  -- prison-jumpsuit band
            manacle = { kind = "cylinder", position = { 0.30, 0.66, 0.05 }, scale = { 0.18, 0.06, 0.18 }, color = C.rust, emissive = 0.5 },
            eye_l = { kind = "sphere", position = { -0.08, 1.04, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.blood, emissive = 1.5 },
            eye_r = { kind = "sphere", position = { 0.08, 1.04, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.blood, emissive = 1.5 },
        },
    },
}

-- The KNIGHT PRISONER: a fallen knight clapped in irons. Slow but durable —
-- wades the blocks behind a battered shield, a broadsword reclaimed from a guard.
Cond.heroes.knight = {
    stats = { hp_max = 130.0, dps = 18.0, cleave = 3, attack_range = 1.30, speed = 2.0, kite_speed = 2.45 },
    actor = {
        name = "Cond_Knight",
        -- texture = Cond.tex.knight,  -- 4-frame artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.54, 0.80, 0.40 }, color = C.metal, emissive = 0.55 },
            head = { kind = "cube", position = { 0.0, 1.12, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.metal, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.36, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.stone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.36, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.stone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.40, 0.54, 0.10 }, scale = { 0.09, 0.78, 0.10 }, color = C.metal, emissive = 0.9 },
            visor = { kind = "cube", position = { 0.0, 1.12, 0.18 }, scale = { 0.30, 0.06, 0.04 }, color = C.black, emissive = 0.2 },
            shield = { kind = "cube", position = { -0.40, 0.58, 0.08 }, scale = { 0.10, 0.56, 0.46 }, color = C.stone, emissive = 0.5 },
            cross = { kind = "cube", position = { 0.40, 0.78, 0.10 }, scale = { 0.26, 0.07, 0.07 }, color = C.metal, emissive = 0.8 },
            shackle = { kind = "cylinder", position = { -0.36, 0.66, 0.05 }, scale = { 0.20, 0.07, 0.20 }, color = C.rust, emissive = 0.5 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde — the gaol garrison. extras give each its silhouette.
-- ---------------------------------------------------------------------------

-- The bolt a Crossbow Sentry looses: a short heavy quarrel that DROPS under
-- gravity, so the sentry must lead a moving hero (projectile.gravity is honoured
-- by creep.lua).
local function crossbow_bolt()
    return {
        kind = "orb", speed = 16.0, cooldown = 1.6, start_y = 1.00, target_y = 0.55,
        particle_size = 0.16, scale = { 0.09, 0.09, 0.56 }, color = C.rust,
        emissive = 1.0, arc = 0.04, gravity = -7.0, impact = true,
        hit_radius = 0.7, flight_grace = 0.10,
    }
end

Cond.archetypes = {
    -- [HEADLINE] DUNGEON GUARD — the baton-swinging melee guard that walks the
    -- blocks. Cheap swarm spine; mode.lua also seats stationary patrol guards as
    -- decoration, this is the same menace the horde can deploy as a card unit.
    dungeon_guard = {
        name = "Dungeon Guard", threat_cost = 1, hp = 11, dps = 3.2, range = 0.70, speed = 2.3,
        color = C.metal, head = C.stone, weapon = C.rust,
        body_scale = { 0.36, 0.56, 0.28 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.30, 0.50, 0.06 }, weapon_scale = { 0.06, 0.46, 0.06 },
        parts = 3, scale = 1.0,
        -- texture = Cond.tex.guard,  -- 6-frame sprite-sheet drop-in
        extras = {
            { name = "Guard_Helm", kind = "cube", position = { 0.0, 0.86, 0.0 }, scale = { 0.28, 0.10, 0.28 }, color = C.metal, emissive = 0.7 },
            { name = "Guard_Visor", kind = "cube", position = { 0.0, 0.80, 0.14 }, scale = { 0.22, 0.05, 0.04 }, color = C.black, emissive = 0.2 },
            { name = "Guard_Baton", kind = "cube", position = { 0.30, 0.48, 0.06 }, scale = { 0.06, 0.40, 0.06 }, color = C.rust, emissive = 0.6 },
            { name = "Guard_Eye", kind = "sphere", position = { 0.0, 0.80, 0.13 }, scale = { 0.09, 0.05, 0.04 }, color = C.blood, emissive = 1.6 },
        },
    },
    -- PRISON HOUND — a starved gaol dog. Fast, frail; the thing that runs down a
    -- kiting hero through the side passages.
    prison_hound = {
        name = "Prison Hound", threat_cost = 1, hp = 6, dps = 2.4, range = 0.5, speed = 3.4,
        color = C.black, head = C.black,
        body_scale = { 0.42, 0.24, 0.26 }, head_pos = { 0.0, 0.40, 0.18 }, head_scale = { 0.20, 0.20, 0.22 },
        parts = 2, scale = 0.85,
        extras = {
            { name = "Hound_Snout", kind = "cube", position = { 0.0, 0.36, 0.30 }, scale = { 0.10, 0.10, 0.18 }, color = C.black, emissive = 0.5 },
            { name = "Hound_Eye", kind = "sphere", position = { 0.0, 0.44, 0.22 }, scale = { 0.08, 0.05, 0.04 }, color = C.blood, emissive = 1.7 },
            { name = "Hound_Tail", kind = "cube", position = { 0.0, 0.40, -0.24 }, scale = { 0.06, 0.06, 0.20 }, color = C.black, emissive = 0.4 },
        },
    },
    -- [HEADLINE-adjacent] CROSSBOW SENTRY — ranged guard; arcs gravity-dropping
    -- quarrels from the wall walks, so the horde answers the four-role deck.
    crossbow_sentry = {
        name = "Crossbow Sentry", threat_cost = 3, hp = 13, dps = 2.6, range = 6.5, speed = 1.2,
        color = C.metal, head = C.stone, weapon = C.rust,
        body_scale = { 0.34, 0.56, 0.26 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.32, 0.62, 0.10 }, weapon_scale = { 0.40, 0.08, 0.08 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = crossbow_bolt(),
        -- texture = Cond.tex.guard,
        extras = {
            { name = "Sentry_Helm", kind = "cube", position = { 0.0, 0.92, 0.0 }, scale = { 0.26, 0.10, 0.26 }, color = C.metal, emissive = 0.7 },
            { name = "Sentry_Stock", kind = "cube", position = { 0.30, 0.62, 0.12 }, scale = { 0.10, 0.10, 0.34 }, color = C.rust, emissive = 0.6 },
            { name = "Sentry_Prod", kind = "cube", position = { 0.30, 0.62, 0.30 }, scale = { 0.34, 0.06, 0.06 }, color = C.rust, emissive = 0.6 },
            { name = "Sentry_Eye", kind = "sphere", position = { 0.0, 0.86, 0.13 }, scale = { 0.09, 0.05, 0.04 }, color = C.blood, emissive = 1.6 },
        },
    },
    -- [HEADLINE] JAILER — the heavy key-holder. Slow and tanky: he anchors a
    -- doorway and clubs anything in reach, the ring of cell keys swinging at his
    -- belt. The horde's elite; in fiction he's the one who works the lockdowns.
    jailer = {
        name = "Jailer", threat_cost = 4, hp = 44, dps = 8.5, range = 1.0, speed = 0.9,
        color = C.stone, head = C.metal, weapon = C.rust,
        body_scale = { 0.62, 0.72, 0.50 }, head_pos = { 0.0, 0.92, 0.0 }, head_scale = { 0.30, 0.30, 0.30 },
        weapon_pos = { 0.46, 0.50, 0.06 }, weapon_scale = { 0.12, 0.56, 0.12 },
        parts = 3, scale = 1.45,
        extras = {
            { name = "Jailer_Hood", kind = "cube", position = { 0.0, 0.98, -0.02 }, scale = { 0.36, 0.20, 0.36 }, color = C.black, emissive = 0.3 },
            { name = "Jailer_Club", kind = "cube", position = { 0.46, 0.46, 0.06 }, scale = { 0.16, 0.40, 0.16 }, color = C.rust, emissive = 0.6 },
            { name = "Jailer_Keyring", kind = "cylinder", position = { -0.34, 0.40, 0.14 }, scale = { 0.22, 0.06, 0.22 }, color = C.torch, emissive = 1.1 },
            { name = "Jailer_Key1", kind = "cube", position = { -0.34, 0.30, 0.14 }, scale = { 0.05, 0.20, 0.05 }, color = C.torch, emissive = 1.0 },
            { name = "Jailer_Key2", kind = "cube", position = { -0.26, 0.31, 0.14 }, scale = { 0.05, 0.18, 0.05 }, color = C.torch, emissive = 1.0 },
            { name = "Jailer_Eye_L", kind = "sphere", position = { -0.10, 0.92, 0.16 }, scale = { 0.09, 0.06, 0.05 }, color = C.blood, emissive = 1.7 },
            { name = "Jailer_Eye_R", kind = "sphere", position = { 0.10, 0.92, 0.16 }, scale = { 0.09, 0.06, 0.05 }, color = C.blood, emissive = 1.7 },
        },
    },
    -- [HEADLINE] WARDEN — the gaol's master. A towering figure with a great
    -- cleaver and a tattered cape; arrives late and breaks the line. mode.lua also
    -- runs a bespoke Warden that HUNTS the hero down the final block — this is that
    -- menace made available to the horde as a brute card.
    warden = {
        name = "The Warden", threat_cost = 6, hp = 80, dps = 10.0, range = 1.10, speed = 1.2,
        color = C.black, head = C.metal, weapon = C.metal,
        body_scale = { 0.76, 0.86, 0.58 }, head_pos = { 0.0, 1.10, -0.04 }, head_scale = { 0.34, 0.34, 0.34 },
        weapon_pos = { 0.52, 0.52, 0.06 }, weapon_scale = { 0.10, 0.84, 0.30 },
        parts = 3, scale = 1.95,
        extras = {
            { name = "Warden_Cape", kind = "cube", position = { 0.0, 0.70, -0.32 }, scale = { 0.70, 0.92, 0.10 }, color = C.blood, emissive = 0.6 },
            { name = "Warden_Crown", kind = "cube", position = { 0.0, 1.34, 0.0 }, scale = { 0.40, 0.12, 0.40 }, color = C.metal, emissive = 0.9 },
            { name = "Warden_Cleaver", kind = "cube", position = { 0.54, 0.62, 0.06 }, scale = { 0.10, 0.62, 0.40 }, color = C.metal, emissive = 0.9 },
            { name = "Warden_Edge", kind = "cube", position = { 0.66, 0.62, 0.06 }, scale = { 0.04, 0.62, 0.40 }, color = C.blood, emissive = 1.0 },
            { name = "Warden_Eye_L", kind = "sphere", position = { -0.12, 1.12, 0.18 }, scale = { 0.11, 0.08, 0.05 }, color = C.torch, emissive = 2.0 },
            { name = "Warden_Eye_R", kind = "sphere", position = { 0.12, 1.12, 0.18 }, scale = { 0.11, 0.08, 0.05 }, color = C.torch, emissive = 2.0 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Cond.roles = {
    swarm = "dungeon_guard",
    ranged = "crossbow_sentry",
    elite = "jailer",
    brute = "warden",
}

return Cond
