-- Plague Quarter — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               plague-bearer/rot-thrower silhouette — no code, just data).
--   * texture = an optional "Objects/plague_quarter/foo.png" painted on a part.
--
-- The headline horde the brief asks for is all here: the PLAGUE BEARER (melee
-- chaff that INFECTS on contact), the ROT THROWER (a ranged caster that lobs an
-- arcing gob which lands as an INFECTION PUDDLE — mode.lua spawns the puddle), the
-- QUARANTINE GUARD (a sealed, tanky enforcer elite who works the quarantine
-- seals), and the PLAGUELORD (the boss — a bloated pestilence-king whose death
-- breaks the line; mode.lua also runs a bespoke Plaguelord that HUNTS the hero
-- through the cathedral and looses an AoE pestilence burst). A CARRION RAT fast-
-- chaser rounds the cast out so the shared 50-card deck's four roles all resolve.
--
-- Sprite-sheet textures (plague_bearer_sheet, rot_thrower_sheet, plaguelord_sheet,
-- torch_sheet) are generated by tools/gen_textures_plague.py and referenced as
-- commented drop-ins below — the same artist hand-off the other modes use. The
-- seamless TILE textures (cobble_floor / infected_wall) and the puddle/barrier
-- sprites ARE wired live, in mode.lua, where they tile across flat geometry.

local Pq = {}

-- The PLAGUE QUARTER palette (mirrors tools/gen_textures_plague.py exactly).
local C = {
    void   = { 0.051, 0.051, 0.000 }, -- #0d0d00 sick black
    dark   = { 0.102, 0.102, 0.000 }, -- #1a1a00 rotted shadow
    stone  = { 0.165, 0.165, 0.000 }, -- #2a2a00 diseased stone
    sick   = { 0.290, 0.400, 0.000 }, -- #4a6600 sickly bile-green
    infect = { 0.000, 0.800, 0.000 }, -- #00cc00 raw infection
    torch  = { 0.800, 0.400, 0.000 }, -- #cc6600 torch fire
    pale   = { 0.62, 0.60, 0.50 },    -- plague-grey flesh / bone
    iron   = { 0.34, 0.34, 0.28 },    -- pitted iron / sealed suit
    blood  = { 0.42, 0.10, 0.06 },    -- old blood / sores
}
Pq.palette = C

-- Texture paths (the engine roots texture paths at Assets/, so these resolve to
-- Assets/Objects/plague_quarter/<file>.png). The generated plague-quarter art is
-- optional; resolve paths only when the asset is present so missing art does not
-- keep hitting material.set_texture during combat.
local TEX = "Objects/plague_quarter/"
local function texture_if_present(name)
    local path = TEX .. name
    if not (fs and fs.find) then return nil end
    local found = fs.find(name, TEX)
    for _, full in ipairs(found or {}) do
        local normalized = tostring(full):gsub("\\", "/")
        if normalized:sub(-#path) == path then return path end
    end
    return nil
end
Pq.tex = {
    floor       = texture_if_present("cobble_floor.png"),
    wall        = texture_if_present("infected_wall.png"),
    puddle      = texture_if_present("infection_puddle_sheet.png"),
    barrier     = texture_if_present("quarantine_barrier.png"),
    torch       = texture_if_present("torch_sheet.png"),
    plague_bearer = texture_if_present("plague_bearer_sheet.png"),
    rot_thrower = texture_if_present("rot_thrower_sheet.png"),
    plaguelord  = texture_if_present("plaguelord_sheet.png"),
}

Pq.theme = {
    accent = { 0.0, 0.80, 0.0, 0.95 },          -- infection-green Souls-grim UI
    floor = { 0.09, 0.09, 0.02 },
    floor_texture = Pq.tex.floor,               -- the cobblestone, wired live
    wall = { 0.102, 0.102, 0.0 },
    spawn_sigil = { 0.0, 0.80, 0.0 },
    aura = { 0.10, 0.55, 0.05, 0.45 },
    hero_body = { 0.165, 0.165, 0.0 },
    hero_trim = { 0.62, 0.60, 0.50 },
    hud_title = "PLAGUE QUARTER",
    win_text = "The cathedral doors seal behind you. The contagion stays in the dark.\nPress R to walk the quarter again  -  M for menu",
    lose_text = "The infection takes you whole. You rot where you fall.\nPress R to walk the quarter again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO classes. mode.lua picks one (ATH_PLAGUE_CLASS, default
-- "plague_doctor"). Both rigs keep the standard part keys (body/head/hand_r/
-- hand_l/foot_r/foot_l/sword) so ath_art's built-in walk/attack clips animate
-- them; extra parts ride the root for flavour. Sprite-sheet skins are commented
-- drop-ins.
-- ---------------------------------------------------------------------------

Pq.heroes = {}

-- The PLAGUE DOCTOR: the beaked physician. Slower of foot, but his herb-stuffed
-- mask buys him a recurring INFECTION IMMUNITY window (mode.lua auto-medicates on
-- a 3s cooldown) — the reflexive answer to the rising sickness.
Pq.heroes.plague_doctor = {
    stats = { hp_max = 96.0, dps = 22.0, cleave = 2, attack_range = 1.20, speed = 2.10, kite_speed = 2.6 },
    -- ATH extensions read by mode.lua's infection system.
    infect_mult = 0.85,                                 -- a touch resistant
    immunity = { window = 1.4, cd = 3.0 },              -- auto-purge window / cooldown
    actor = {
        name = "Pq_PlagueDoctor",
        -- texture = Pq.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.42, 0.72, 0.30 }, color = C.dark, emissive = 0.5 },
            head = { kind = "sphere", position = { 0.0, 1.06, 0.0 }, scale = { 0.32, 0.32, 0.32 }, color = C.pale, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.pale, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.pale, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.void, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.32, 0.50, 0.10 }, scale = { 0.05, 0.50, 0.05 }, color = C.iron, emissive = 0.9 },  -- the cane
            -- The beaked mask: a long bone snout + dark glass goggles.
            beak = { kind = "cube", position = { 0.0, 1.02, 0.20 }, scale = { 0.10, 0.10, 0.28 }, color = C.pale, emissive = 0.5 },
            goggle_l = { kind = "sphere", position = { -0.09, 1.10, 0.16 }, scale = { 0.08, 0.08, 0.05 }, color = C.void, emissive = 0.3 },
            goggle_r = { kind = "sphere", position = { 0.09, 1.10, 0.16 }, scale = { 0.08, 0.08, 0.05 }, color = C.void, emissive = 0.3 },
            hat = { kind = "cube", position = { 0.0, 1.26, 0.0 }, scale = { 0.40, 0.10, 0.40 }, color = C.void, emissive = 0.3 },  -- wide brim
            crown = { kind = "cube", position = { 0.0, 1.36, 0.0 }, scale = { 0.20, 0.16, 0.20 }, color = C.void, emissive = 0.3 },
            satchel = { kind = "cube", position = { -0.30, 0.42, 0.10 }, scale = { 0.16, 0.20, 0.12 }, color = C.blood, emissive = 0.4 },
            vial = { kind = "sphere", position = { -0.30, 0.56, 0.14 }, scale = { 0.08, 0.10, 0.08 }, color = C.infect, emissive = 1.4 },
        },
    },
}

-- The IRON IMMUNE: a survivor sealed head-to-toe in pitted plague-iron. Slow and
-- heavy, but the contagion barely reaches him through the riveted plate — his
-- INFECTION RATE is far lower. The attrition answer to the quarter.
Pq.heroes.iron_immune = {
    stats = { hp_max = 136.0, dps = 18.0, cleave = 3, attack_range = 1.30, speed = 2.00, kite_speed = 2.45, armor = 1 },
    infect_mult = 0.45,                                 -- the sealed suit resists rot
    actor = {
        name = "Pq_IronImmune",
        -- texture = Pq.tex... (artist sprite-sheet drop-in)
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.56, 0.82, 0.42 }, color = C.iron, emissive = 0.55 },
            head = { kind = "cube", position = { 0.0, 1.12, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.iron, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.38, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.stone, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.38, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.stone, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.void, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.42, 0.54, 0.10 }, scale = { 0.09, 0.80, 0.10 }, color = C.iron, emissive = 0.9 },
            visor = { kind = "cube", position = { 0.0, 1.12, 0.18 }, scale = { 0.30, 0.06, 0.04 }, color = C.void, emissive = 0.2 },
            filter = { kind = "cylinder", position = { 0.0, 1.02, 0.18 }, scale = { 0.12, 0.10, 0.12 }, color = C.sick, emissive = 0.8 },  -- breath filter
            shield = { kind = "cube", position = { -0.42, 0.58, 0.08 }, scale = { 0.10, 0.58, 0.46 }, color = C.iron, emissive = 0.5 },
            shield_boss = { kind = "sphere", position = { -0.48, 0.58, 0.08 }, scale = { 0.12, 0.12, 0.12 }, color = C.sick, emissive = 1.0 },
            rivet_l = { kind = "sphere", position = { -0.20, 0.78, 0.22 }, scale = { 0.05, 0.05, 0.05 }, color = C.pale, emissive = 0.6 },
            rivet_r = { kind = "sphere", position = { 0.20, 0.78, 0.22 }, scale = { 0.05, 0.05, 0.05 }, color = C.pale, emissive = 0.6 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde — everything is OF the plague: bloated, weeping, sealed, rotten.
-- extras give each its silhouette.
-- ---------------------------------------------------------------------------

-- The gob a Rot Thrower lobs: a heavy mote of infection HURLED up off the cobbles
-- so it ARCS and DROPS under gravity (projectile.gravity is honoured by creep.lua).
-- Where it lands, mode.lua blooms an infection puddle.
local function rot_gob()
    return {
        kind = "orb", speed = 11.0, cooldown = 1.8, start_y = 0.95, target_y = 0.40,
        particle_size = 0.22, scale = { 0.24, 0.24, 0.24 }, color = C.infect,
        emissive = 1.4, arc = 0.30, gravity = -7.0, impact = true,
        hit_radius = 0.80, flight_grace = 0.10,
        -- texture = Pq.tex... (the gob is drawn from the orb scale)
    }
end

Pq.archetypes = {
    -- [HEADLINE] PLAGUE BEARER — a weeping, pox-ridden wretch that shambles at the
    -- hero and INFECTS on contact (mode.lua reads plague_bearer proximity and
    -- pumps the infection bar). The cheap swarm spine of the horde.
    plague_bearer = {
        name = "Plague Bearer", threat_cost = 1, hp = 10, dps = 3.0, range = 0.70, speed = 2.40,
        color = C.sick, head = C.pale, weapon = C.infect,
        body_scale = { 0.36, 0.54, 0.28 }, head_scale = { 0.24, 0.24, 0.24 },
        parts = 3, scale = 1.0,
        weapon_pos = { 0.26, 0.50, 0.08 }, weapon_scale = { 0.06, 0.34, 0.06 },
        -- texture = Pq.tex.plague_bearer,  -- 6-frame sprite-sheet drop-in
        extras = {
            { name = "Bearer_Pustule", kind = "sphere", position = { -0.14, 0.62, 0.16 }, scale = { 0.12, 0.12, 0.10 }, color = C.infect, emissive = 1.3 },
            { name = "Bearer_Sore", kind = "sphere", position = { 0.16, 0.40, 0.14 }, scale = { 0.10, 0.10, 0.08 }, color = C.blood, emissive = 0.8 },
            { name = "Bearer_Claw", kind = "cube", position = { 0.26, 0.50, 0.10 }, scale = { 0.05, 0.30, 0.05 }, color = C.pale, emissive = 0.6, rotation = { 0.0, 0.0, 18.0 } },
            { name = "Bearer_Drip", kind = "cube", position = { 0.0, 0.26, 0.0 }, scale = { 0.26, 0.08, 0.20 }, color = C.infect, emissive = 1.1 },
            { name = "Bearer_Eye", kind = "sphere", position = { 0.0, 0.78, 0.13 }, scale = { 0.09, 0.05, 0.04 }, color = C.infect, emissive = 1.7 },
        },
    },
    -- CARRION RAT — a swollen, plague-bloated rat. Fast and frail; the thing that
    -- runs down a kiting hero between the puddles.
    carrion_rat = {
        name = "Carrion Rat", threat_cost = 1, hp = 6, dps = 2.2, range = 0.5, speed = 3.4,
        color = C.dark, head = C.dark,
        body_scale = { 0.42, 0.22, 0.26 }, head_pos = { 0.0, 0.36, 0.18 }, head_scale = { 0.18, 0.18, 0.20 },
        parts = 2, scale = 0.85,
        extras = {
            { name = "Rat_Snout", kind = "cube", position = { 0.0, 0.32, 0.30 }, scale = { 0.09, 0.08, 0.16 }, color = C.pale, emissive = 0.5 },
            { name = "Rat_Boil", kind = "sphere", position = { 0.0, 0.42, -0.04 }, scale = { 0.12, 0.12, 0.12 }, color = C.sick, emissive = 1.0 },
            { name = "Rat_Eye", kind = "sphere", position = { 0.0, 0.40, 0.22 }, scale = { 0.07, 0.05, 0.04 }, color = C.infect, emissive = 1.7 },
            { name = "Rat_Tail", kind = "cube", position = { 0.0, 0.34, -0.26 }, scale = { 0.05, 0.05, 0.22 }, color = C.blood, emissive = 0.4 },
        },
    },
    -- [HEADLINE] ROT THROWER — a hunched caster that hurls arcing gobs of rot from
    -- range; each lands as an infection puddle (mode.lua). Holds the rear and
    -- poisons the ground the hero must cross. The deck's "ranged".
    rot_thrower = {
        name = "Rot Thrower", threat_cost = 3, hp = 13, dps = 2.4, range = 6.5, speed = 1.15,
        color = C.stone, head = C.sick, weapon = C.infect,
        body_scale = { 0.36, 0.56, 0.28 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.30, 0.66, 0.12 }, weapon_scale = { 0.16, 0.16, 0.16 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = rot_gob(),
        -- texture = Pq.tex.rot_thrower,  -- 5-frame sprite-sheet drop-in
        extras = {
            { name = "Thrower_Cowl", kind = "cube", position = { 0.0, 0.86, -0.02 }, scale = { 0.30, 0.18, 0.30 }, color = C.void, emissive = 0.3 },
            { name = "Thrower_Censer", kind = "sphere", position = { 0.30, 0.64, 0.16 }, scale = { 0.16, 0.16, 0.16 }, color = C.dark, emissive = 0.5 },
            { name = "Thrower_Gob", kind = "sphere", position = { 0.30, 0.64, 0.24 }, scale = { 0.12, 0.12, 0.12 }, color = C.infect, emissive = 1.7 },
            { name = "Thrower_Sore", kind = "sphere", position = { -0.16, 0.50, 0.16 }, scale = { 0.10, 0.10, 0.08 }, color = C.infect, emissive = 1.2 },
            { name = "Thrower_Eye", kind = "sphere", position = { 0.0, 0.78, 0.13 }, scale = { 0.09, 0.05, 0.04 }, color = C.infect, emissive = 1.6 },
        },
    },
    -- [HEADLINE] QUARANTINE GUARD — a sealed enforcer in riveted plague-plate. Slow
    -- and heavy: he anchors a quarantine seal and clubs anything that nears it. The
    -- horde's elite; in fiction he is the one who slams the diseased barriers down.
    quarantine_guard = {
        name = "Quarantine Guard", threat_cost = 4, hp = 46, dps = 8.5, range = 1.0, speed = 0.9,
        color = C.iron, head = C.iron, weapon = C.stone,
        body_scale = { 0.62, 0.74, 0.50 }, head_pos = { 0.0, 0.94, 0.0 }, head_scale = { 0.30, 0.30, 0.30 },
        weapon_pos = { 0.48, 0.50, 0.06 }, weapon_scale = { 0.14, 0.56, 0.14 },
        parts = 3, scale = 1.45,
        extras = {
            { name = "Guard_Hood", kind = "cube", position = { 0.0, 1.00, -0.02 }, scale = { 0.36, 0.20, 0.36 }, color = C.void, emissive = 0.3 },
            { name = "Guard_Filter", kind = "cylinder", position = { 0.0, 0.88, 0.16 }, scale = { 0.12, 0.10, 0.12 }, color = C.sick, emissive = 0.9 },
            { name = "Guard_Maul", kind = "cube", position = { 0.48, 0.46, 0.06 }, scale = { 0.18, 0.40, 0.18 }, color = C.stone, emissive = 0.6 },
            { name = "Guard_Lantern", kind = "sphere", position = { -0.36, 0.46, 0.14 }, scale = { 0.16, 0.18, 0.16 }, color = C.sick, emissive = 1.3 },
            { name = "Guard_Eye_L", kind = "sphere", position = { -0.10, 0.94, 0.16 }, scale = { 0.09, 0.06, 0.05 }, color = C.infect, emissive = 1.7 },
            { name = "Guard_Eye_R", kind = "sphere", position = { 0.10, 0.94, 0.16 }, scale = { 0.09, 0.06, 0.05 }, color = C.infect, emissive = 1.7 },
        },
    },
    -- [HEADLINE] PLAGUELORD — the pestilence-king. A vast bloated horror crowned in
    -- bone, weeping contagion; arrives late and breaks the line. mode.lua also runs
    -- a bespoke Plaguelord that HUNTS the hero through the cathedral and looses an
    -- AoE PESTILENCE BURST — this is that menace made available as a brute card.
    plaguelord = {
        name = "The Plaguelord", threat_cost = 6, hp = 92, dps = 10.5, range = 1.10, speed = 1.15,
        color = C.sick, head = C.dark, weapon = C.infect,
        body_scale = { 0.86, 0.92, 0.66 }, head_pos = { 0.0, 1.12, -0.04 }, head_scale = { 0.40, 0.38, 0.40 },
        weapon_pos = { 0.56, 0.52, 0.06 }, weapon_scale = { 0.18, 0.86, 0.20 },
        parts = 3, scale = 2.05,
        -- texture = Pq.tex.plaguelord,  -- 8-frame 128x128 sprite-sheet drop-in
        extras = {
            { name = "Lord_Crown", kind = "cube", position = { 0.0, 1.38, 0.0 }, scale = { 0.44, 0.14, 0.44 }, color = C.pale, emissive = 0.8 },
            { name = "Lord_Boil_L", kind = "sphere", position = { -0.32, 0.72, 0.30 }, scale = { 0.20, 0.20, 0.18 }, color = C.infect, emissive = 1.4 },
            { name = "Lord_Boil_R", kind = "sphere", position = { 0.30, 0.52, 0.32 }, scale = { 0.18, 0.18, 0.16 }, color = C.infect, emissive = 1.4 },
            { name = "Lord_Ribs", kind = "cube", position = { 0.0, 0.76, 0.34 }, scale = { 0.58, 0.50, 0.06 }, color = C.pale, emissive = 0.6 },
            { name = "Lord_Maw", kind = "cube", position = { 0.0, 1.06, 0.22 }, scale = { 0.30, 0.10, 0.10 }, color = C.void, emissive = 0.4 },
            { name = "Lord_Eye_L", kind = "sphere", position = { -0.12, 1.16, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.infect, emissive = 2.0 },
            { name = "Lord_Eye_R", kind = "sphere", position = { 0.12, 1.16, 0.20 }, scale = { 0.11, 0.09, 0.05 }, color = C.infect, emissive = 2.0 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Pq.roles = {
    swarm = "plague_bearer",
    ranged = "rot_thrower",
    elite = "quarantine_guard",
    brute = "plaguelord",
}

return Pq
