-- Catacombs — the cast.
--
-- Pure DATA. Every creature is a horde/creep.lua-compatible archetype, plus the
-- two ATH extensions the shared Duel honours:
--   * extras  = decorative ath_art PART specs welded on after build (the
--               creature's signature silhouette — no code, just data).
--   * texture = an optional "Textures/modes/catacombs/foo.png" painted on a part.
--
-- The headline horde cast the brief asks for is here: the CRYPT WALKER (melee
-- skeleton), the WALL SPIKE TRAP (a creeping floor hazard), and the TOMB ARCHER
-- (a ranged skeleton whose arrow drops under gravity). Two more skeletal variants
-- round the cast out so the shared 50-card deck's four roles all resolve.
--
-- Sprite-sheet textures (skeleton_sheet.png, hero_*_sheet.png, torch_sheet.png)
-- are generated by tools/gen_textures_catacombs.py and referenced as commented
-- drop-ins below — the same artist hand-off the other modes use. The seamless
-- TILE textures (wall_tile / floor_tile / background) ARE wired live, in
-- mode.lua, where they tile across flat geometry instead of a single body cube.

local Cata = {}

-- The CATACOMBS palette (mirrors tools/gen_textures_catacombs.py exactly).
local C = {
    black  = { 0.05, 0.05, 0.05 },   -- #0d0d0d
    stone  = { 0.165, 0.165, 0.165 },-- #2a2a2a
    hilite = { 0.42, 0.42, 0.42 },   -- #6b6b6b
    blood  = { 0.80, 0.0, 0.0 },     -- #cc0000
    torch  = { 1.0, 0.667, 0.0 },    -- #ffaa00
    bone   = { 0.78, 0.77, 0.72 },   -- skeletal off-white
    rust   = { 0.45, 0.30, 0.18 },   -- corroded iron
}
Cata.palette = C

-- Texture paths (engine roots at Assets/). Generated by the python tool.
local TEX = "Textures/modes/catacombs/"
Cata.tex = {
    wall = TEX .. "wall_tile.png",
    floor = TEX .. "floor_tile.png",
    background = TEX .. "background.png",
    skeleton = TEX .. "skeleton_sheet.png",
    torch = TEX .. "torch_sheet.png",
    hero_knight = TEX .. "hero_knight_sheet.png",
    hero_rogue = TEX .. "hero_rogue_sheet.png",
}

Cata.theme = {
    accent = { 0.80, 0.05, 0.05, 0.95 },        -- blood-red, like a Souls bonfire UI
    floor = { 0.10, 0.10, 0.10 },
    floor_texture = Cata.tex.floor,             -- the tomb flagstone, wired live
    wall = { 0.13, 0.13, 0.13 },
    spawn_sigil = { 0.80, 0.05, 0.05 },
    aura = { 0.80, 0.10, 0.10, 0.45 },
    hero_body = { 0.165, 0.165, 0.165 },
    hero_trim = { 0.42, 0.42, 0.42 },
    hud_title = "CATACOMBS",
    win_text = "The corridor falls silent. The dead keep their tombs.\nPress R to descend again  -  M for menu",
    lose_text = "The hero is dragged beneath the flagstones.\nPress R to descend again  -  M for menu",
}

-- ---------------------------------------------------------------------------
-- Heroes — TWO classes. mode.lua picks one (ATH_CATA_CLASS, default "knight").
-- Both rigs keep the standard part keys (body/head/hand_r/hand_l/foot_r/foot_l/
-- sword) so ath_art's built-in walk/attack clips animate them; extra parts ride
-- the root for flavour. Sprite-sheet skins are commented drop-ins.
-- ---------------------------------------------------------------------------

-- The KNIGHT: heavy, armoured, cleaving. Slow but durable — wades the corridor.
Cata.heroes = {}
Cata.heroes.knight = {
    stats = { hp_max = 120.0, dps = 19.0, cleave = 3, attack_range = 1.30, speed = 2.05, kite_speed = 2.5 },
    actor = {
        name = "Cata_Knight",
        -- texture = Cata.tex.hero_knight,  -- artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.56, 0.0 }, scale = { 0.52, 0.78, 0.38 }, color = C.stone, emissive = 0.55 },
            head = { kind = "cube", position = { 0.0, 1.10, 0.0 }, scale = { 0.34, 0.32, 0.34 }, color = C.stone, emissive = 0.5 },
            hand_r = { kind = "sphere", position = { 0.34, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.hilite, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.34, 0.66, 0.05 }, scale = { 0.16, 0.16, 0.16 }, color = C.hilite, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.14, 0.05, 0.0 }, scale = { 0.20, 0.10, 0.26 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.38, 0.52, 0.10 }, scale = { 0.09, 0.74, 0.10 }, color = C.hilite, emissive = 0.9 },
            visor = { kind = "cube", position = { 0.0, 1.10, 0.18 }, scale = { 0.30, 0.06, 0.04 }, color = C.black, emissive = 0.2 },
            crest = { kind = "cube", position = { 0.0, 1.34, 0.0 }, scale = { 0.06, 0.18, 0.10 }, color = C.torch, emissive = 1.3 },
            cross = { kind = "cube", position = { 0.38, 0.74, 0.10 }, scale = { 0.26, 0.07, 0.07 }, color = C.hilite, emissive = 0.8 },
        },
    },
}

-- The ROGUE: lean, fast, twin-bladed. Frail but high-DPS and slippery (dash).
Cata.heroes.rogue = {
    stats = { hp_max = 80.0, dps = 27.0, cleave = 2, attack_range = 1.15, speed = 2.6, kite_speed = 3.2, dash = 1 },
    actor = {
        name = "Cata_Rogue",
        -- texture = Cata.tex.hero_rogue,  -- artist sprite-sheet drop-in
        parts = {
            body = { kind = "cube", position = { 0.0, 0.54, 0.0 }, scale = { 0.40, 0.70, 0.30 }, color = { 0.11, 0.11, 0.11 }, emissive = 0.5 },
            head = { kind = "sphere", position = { 0.0, 1.06, 0.0 }, scale = { 0.34, 0.34, 0.34 }, color = { 0.11, 0.11, 0.11 }, emissive = 0.45 },
            hand_r = { kind = "sphere", position = { 0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.hilite, emissive = 0.5 },
            hand_l = { kind = "sphere", position = { -0.30, 0.64, 0.05 }, scale = { 0.13, 0.13, 0.13 }, color = C.hilite, emissive = 0.5 },
            foot_r = { kind = "cube", position = { 0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            foot_l = { kind = "cube", position = { -0.12, 0.05, 0.0 }, scale = { 0.16, 0.09, 0.22 }, color = C.black, emissive = 0.3 },
            sword = { kind = "cube", position = { 0.32, 0.46, 0.10 }, scale = { 0.06, 0.50, 0.06 }, color = C.hilite, emissive = 0.9 },
            dagger_l = { kind = "cube", position = { -0.32, 0.46, 0.10 }, scale = { 0.06, 0.40, 0.06 }, color = C.hilite, emissive = 0.9 },
            hood = { kind = "cube", position = { 0.0, 1.22, -0.02 }, scale = { 0.30, 0.18, 0.30 }, color = { 0.08, 0.08, 0.08 }, emissive = 0.3 },
            eye_l = { kind = "sphere", position = { -0.08, 1.06, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.blood, emissive = 1.6 },
            eye_r = { kind = "sphere", position = { 0.08, 1.06, 0.16 }, scale = { 0.05, 0.05, 0.04 }, color = C.blood, emissive = 1.6 },
        },
    },
}

-- ---------------------------------------------------------------------------
-- The horde. A skull-and-bone aesthetic throughout (extras give each silhouette).
-- ---------------------------------------------------------------------------

-- The arrow a Tomb Archer looses: a long thin bolt that DROPS under gravity, so
-- the archer must lead a moving hero (projectile.gravity is honoured by creep.lua).
local function tomb_arrow()
    return {
        kind = "orb", speed = 15.0, cooldown = 1.5, start_y = 1.05, target_y = 0.55,
        particle_size = 0.18, scale = { 0.10, 0.10, 0.62 }, color = C.bone,
        emissive = 1.0, arc = 0.04, gravity = -7.0, impact = true,
        hit_radius = 0.7, flight_grace = 0.10,
        -- texture = Cata.tex... (arrows are drawn from the elongated scale)
    }
end

Cata.archetypes = {
    -- [HEADLINE] CRYPT WALKER — the shambling melee skeleton. Cheap swarm spine.
    crypt_walker = {
        name = "Crypt Walker", threat_cost = 1, hp = 10, dps = 3.2, range = 0.65, speed = 2.25,
        color = C.bone, head = C.bone, body_scale = { 0.34, 0.52, 0.26 }, head_scale = { 0.24, 0.24, 0.24 },
        parts = 2, scale = 1.0,
        -- texture = Cata.tex.skeleton,  -- 8-frame sprite-sheet drop-in
        extras = {
            { name = "Walker_Rib", kind = "cube", position = { 0.0, 0.52, 0.0 }, scale = { 0.30, 0.06, 0.22 }, color = C.bone, emissive = 0.6 },
            { name = "Walker_Rib2", kind = "cube", position = { 0.0, 0.40, 0.0 }, scale = { 0.26, 0.06, 0.20 }, color = C.bone, emissive = 0.6 },
            { name = "Walker_Eye", kind = "sphere", position = { 0.0, 0.84, 0.12 }, scale = { 0.10, 0.06, 0.04 }, color = C.blood, emissive = 1.7 },
            { name = "Walker_Blade", kind = "cube", position = { 0.26, 0.50, 0.06 }, scale = { 0.05, 0.46, 0.05 }, color = C.rust, emissive = 0.7 },
        },
    },
    -- A faster, frailer skeleton — the thing that runs down a kiting hero.
    skitter_bones = {
        name = "Skitterbones", threat_cost = 1, hp = 6, dps = 2.2, range = 0.5, speed = 3.3,
        color = C.bone, head = C.bone, body_scale = { 0.40, 0.24, 0.26 }, head_pos = { 0.0, 0.40, 0.18 }, head_scale = { 0.20, 0.20, 0.22 },
        parts = 2, scale = 0.85,
        extras = {
            { name = "Skitter_Spine", kind = "cube", position = { 0.0, 0.42, -0.06 }, scale = { 0.06, 0.10, 0.34 }, color = C.bone, emissive = 0.6 },
            { name = "Skitter_Eye", kind = "sphere", position = { 0.0, 0.42, 0.20 }, scale = { 0.08, 0.05, 0.04 }, color = C.blood, emissive = 1.6 },
        },
    },
    -- [HEADLINE] TOMB ARCHER — ranged skeleton; arcs gravity-dropping arrows.
    tomb_archer = {
        name = "Tomb Archer", threat_cost = 3, hp = 13, dps = 2.6, range = 6.5, speed = 1.2,
        color = C.bone, head = C.bone, weapon = C.rust,
        body_scale = { 0.34, 0.56, 0.26 }, head_scale = { 0.24, 0.24, 0.24 },
        weapon_pos = { 0.34, 0.62, 0.06 }, weapon_scale = { 0.06, 0.78, 0.06 },
        parts = 3, scale = 1.05, hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
        projectile = tomb_arrow(),
        -- texture = Cata.tex.skeleton,
        extras = {
            { name = "Archer_Bow", kind = "cylinder", position = { 0.36, 0.66, 0.06 }, scale = { 0.06, 0.62, 0.06 }, color = C.rust, emissive = 0.6, rotation = { 0.0, 0.0, 12.0 } },
            { name = "Archer_Quiver", kind = "cube", position = { -0.18, 0.70, -0.14 }, scale = { 0.10, 0.32, 0.10 }, color = C.rust, emissive = 0.5 },
            { name = "Archer_Eye", kind = "sphere", position = { 0.0, 0.92, 0.12 }, scale = { 0.10, 0.06, 0.04 }, color = C.blood, emissive = 1.7 },
        },
    },
    -- [HEADLINE] WALL SPIKE TRAP — a barely-creeping floor hazard bristling with
    -- iron spikes. Slow and tanky: it anchors ground and gores anything in reach
    -- (the dynamic corridor wall-traps are mode.lua's signature mechanic; this is
    -- the same menace made mobile so the horde can deploy it as a unit -> elite).
    wall_spike_trap = {
        name = "Wall Spike Trap", threat_cost = 4, hp = 40, dps = 8.0, range = 1.0, speed = 0.55,
        color = C.stone, head = C.stone, body_scale = { 0.66, 0.40, 0.58 }, head_pos = { 0.0, 0.46, 0.0 }, head_scale = { 0.30, 0.18, 0.30 },
        parts = 2, scale = 1.35,
        extras = {
            { name = "Spike_1", kind = "cylinder", position = { -0.22, 0.62, -0.18 }, scale = { 0.10, 0.40, 0.10 }, color = C.hilite, emissive = 0.7 },
            { name = "Spike_2", kind = "cylinder", position = { 0.22, 0.66, -0.10 }, scale = { 0.10, 0.46, 0.10 }, color = C.hilite, emissive = 0.7 },
            { name = "Spike_3", kind = "cylinder", position = { 0.0, 0.64, 0.20 }, scale = { 0.10, 0.42, 0.10 }, color = C.hilite, emissive = 0.7 },
            { name = "Spike_4", kind = "cylinder", position = { -0.26, 0.60, 0.16 }, scale = { 0.09, 0.34, 0.09 }, color = C.hilite, emissive = 0.7 },
            { name = "Trap_Gore", kind = "cube", position = { 0.0, 0.30, 0.0 }, scale = { 0.50, 0.10, 0.44 }, color = C.blood, emissive = 0.9 },
        },
    },
    -- The brute: a towering bone colossus that arrives late and breaks the line.
    bone_colossus = {
        name = "Bone Colossus", threat_cost = 6, hp = 70, dps = 9.5, range = 1.05, speed = 1.15,
        color = C.bone, head = C.bone, weapon = C.rust,
        body_scale = { 0.78, 0.82, 0.60 }, head_pos = { 0.0, 1.06, -0.04 }, head_scale = { 0.38, 0.36, 0.38 },
        weapon_pos = { 0.50, 0.50, 0.06 }, weapon_scale = { 0.18, 0.78, 0.18 },
        parts = 3, scale = 1.95,
        extras = {
            { name = "Colossus_Horn_L", kind = "cylinder", position = { -0.18, 1.34, 0.0 }, scale = { 0.10, 0.30, 0.10 }, color = C.bone, emissive = 0.8, rotation = { 0.0, 0.0, 24.0 } },
            { name = "Colossus_Horn_R", kind = "cylinder", position = { 0.18, 1.34, 0.0 }, scale = { 0.10, 0.30, 0.10 }, color = C.bone, emissive = 0.8, rotation = { 0.0, 0.0, -24.0 } },
            { name = "Colossus_Ribs", kind = "cube", position = { 0.0, 0.66, 0.30 }, scale = { 0.52, 0.46, 0.06 }, color = C.bone, emissive = 0.7 },
            { name = "Colossus_Eye_L", kind = "sphere", position = { -0.12, 1.10, 0.18 }, scale = { 0.10, 0.08, 0.05 }, color = C.blood, emissive = 1.9 },
            { name = "Colossus_Eye_R", kind = "sphere", position = { 0.12, 1.10, 0.18 }, scale = { 0.10, 0.08, 0.05 }, color = C.blood, emissive = 1.9 },
        },
    },
}

-- The four level-agnostic roles, mapped onto this cast so the shared deck works.
Cata.roles = {
    swarm = "crypt_walker",
    ranged = "tomb_archer",
    elite = "wall_spike_trap",
    brute = "bone_colossus",
}

return Cata
