-- Alien Hive — the cast (DATA only).
--
-- A glowing chunky-cartoon alien arena: acid greens, hive purples, bio-teal. Every
-- creature is a FLAT 2D SPRITE — a horde/creep.lua archetype with the ATH
-- `sprite = true` flag, so the shared Duel paints its texture through the emissive
-- slot (alpha-cut) and billboards the thin body slab at the iso camera each frame,
-- the same way the hero renders. "Each enemy its own texture" is pure data:
--   * texture = "Textures/modes/alien_hive/<file>.png"  (generated by
--     tools/gen_textures_alien_hive.py; engine roots image paths at Assets/).
--   * sprite  = true                                     (flat billboard sprite).
-- Missing PNG -> the creature falls back to its flat `color` silhouette.
--
-- Roles map the four card/spawn roles onto this cast; the stinger flier rides in
-- through auto_mix.
--
-- Aesthetic: chunky cartoon, bold dark outlines, vibrant glowing fills,
-- cute-grotesque aliens versus one armoured vanguard hero.

local Hive = {}

-- ---- Palette (0..1) — bioluminescent alien hive ----------------------------
local C = {
    hive_dk    = { 0.16, 0.07, 0.22 },
    hive       = { 0.34, 0.16, 0.46 },
    acid       = { 0.62, 0.95, 0.24 },
    acid_dk    = { 0.40, 0.66, 0.16 },
    teal       = { 0.20, 0.82, 0.74 },
    grub       = { 0.74, 0.40, 0.86 },
    carapace   = { 0.30, 0.24, 0.40 },
    behemoth   = { 0.46, 0.78, 0.30 },
    stinger    = { 0.96, 0.82, 0.24 },
    bone       = { 0.88, 0.86, 0.78 },
    steel      = { 0.62, 0.70, 0.82 },
}
Hive.palette = C

local TEX = "Textures/modes/alien_hive/"
Hive.tex = {
    floor     = TEX .. "floor.png",
    hero      = TEX .. "hero_vanguard.png",
    acid      = TEX .. "acid_pool.png",
    grub      = TEX .. "grub.png",
    floater   = TEX .. "spore_floater.png",
    carapace  = TEX .. "carapace.png",
    behemoth  = TEX .. "behemoth.png",
    stinger   = TEX .. "stinger.png",
}

Hive.theme = {
    accent        = { 0.62, 0.95, 0.24, 0.95 },
    floor         = { 0.16, 0.08, 0.22 },          -- tint under the hive-floor texture
    floor_texture = Hive.tex.floor,
    wall          = { 0.22, 0.10, 0.30 },
    spawn_sigil   = { 0.62, 0.95, 0.24 },          -- acid-green spawn rings
    aura          = { 0.20, 0.82, 0.74, 0.5 },
    hud_title     = "ALIEN HIVE",
    win_text      = "The hive is scoured; its glow gutters out.\nPress R to run it back  -  M for menu",
    lose_text     = "The hero is dissolved into the brood.\nPress R to run it back  -  M for menu",
}

-- ---- Hero: an armoured vanguard, one flat billboard sprite ------------------
Hive.hero_actor = {
    name = "Hive_Vanguard",
    scale = 1.0,
    billboard = true,
    billboard_parts = { "body" },
    parts = {
        body = {
            kind = "quad", quad_width = 1.6, quad_height = 2.05,
            position = { 0.0, 1.0, 0.0 },
            color = { 1.0, 1.0, 1.0 }, emissive = 1.0, emissive_texture = true,
            texture = Hive.tex.hero,
        },
    },
}

-- ---- The cast — five flat-sprite hive horrors -------------------------------
Hive.archetypes = {
    -- GRUB — the swarm. A little purple maggot-thing that scuttles fast.
    grub = {
        name = "Grub", threat_cost = 1, hp = 6, dps = 2.3, range = 0.5, speed = 2.8,
        color = C.grub, head = C.grub,
        sprite = true, texture = Hive.tex.grub,
        parts = 2, scale = 0.82,
        body_pos = { 0.0, 0.56, 0.0 }, body_scale = { 0.96, 0.94, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- SPORE FLOATER — the ranged anchor. A drifting acid-jelly that hangs back
    -- and spits (a stand-off damage range in the Duel). Flies (ignores terrain).
    spore_floater = {
        name = "Spore Floater", threat_cost = 3, hp = 12, dps = 2.6, range = 6.0, speed = 1.2,
        color = C.teal, head = C.teal,
        sprite = true, texture = Hive.tex.floater, flies = true,
        parts = 2, scale = 1.05,
        body_pos = { 0.0, 1.05, 0.0 }, body_scale = { 1.02, 1.10, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
        hold_range = 6.0, anchor_hold = true, needs_los = true, los_reposition_seconds = 2.0,
    },
    -- CARAPACE — the elite. An armoured beetle-alien; the wall the cleave chews.
    carapace = {
        name = "Carapace", threat_cost = 4, hp = 36, dps = 6.8, range = 0.95, speed = 1.5,
        color = C.carapace, head = C.carapace,
        sprite = true, texture = Hive.tex.carapace,
        parts = 2, scale = 1.22,
        body_pos = { 0.0, 0.70, 0.0 }, body_scale = { 1.18, 1.16, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- BEHEMOTH — the brute. A towering tentacled blob that lumbers and crushes.
    behemoth = {
        name = "Behemoth", threat_cost = 6, hp = 80, dps = 9.5, range = 1.05, speed = 0.95,
        color = C.behemoth, head = C.behemoth,
        sprite = true, texture = Hive.tex.behemoth,
        parts = 2, scale = 1.72,
        body_pos = { 0.0, 0.82, 0.0 }, body_scale = { 1.26, 1.42, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
    -- STINGER — the flier. A fast wasp-alien that ignores terrain and dives.
    stinger = {
        name = "Stinger", threat_cost = 2, hp = 8, dps = 3.2, range = 0.55, speed = 3.4,
        color = C.stinger, head = C.stinger,
        sprite = true, texture = Hive.tex.stinger, flies = true,
        parts = 2, scale = 0.95,
        body_pos = { 0.0, 1.10, 0.0 }, body_scale = { 1.16, 0.92, 0.05 },
        head_scale = { 0.001, 0.001, 0.001 },
    },
}

Hive.roles = {
    swarm  = "grub",
    ranged = "spore_floater",
    elite  = "carapace",
    brute  = "behemoth",
}

return Hive
